### ISSUE TITLE
Can't change backlight to custom via GUI

### ISSUE THREAD

**Issue by veronikazaglotova** [pixeltris/GK6X#100]
I click a color, click on keys I want to change, it doesn't work. I make a new custom backlight file, doesn't work. I click a built-in file, it works but I don't really want these. I edit a built-in file, it doesn't work.

**Comment by pixeltris** [comment]
If you're referring to the key-press lighting that isn't implemented https://github.com/pixeltris/GK6X/issues/93

If you're referring to the multiple layers of lighting that you can assign; some keyboards don't support this functionality, and can only modify the default layer lighting (up to 5 slots in the GUI). This has been tested on Windows/Mac, not sure if the Linux version has issues with this.

**Comment by veronikazaglotova** [comment]
W8 a sec, I'll record a vid

**Comment by veronikazaglotova** [comment]
https://www.youtube.com/watch?v=D-XMIYw9JlA
Also: when I change the backlight file and load it to my keyboard, it doesn't load the file at all, but after I restart the server and the page it works flawlessly.

**Comment by pixeltris** [comment]
Thanks for the video. https://github.com/pixeltris/GK6X/commit/e254296dee03e283d1502cc00145300ba1b661b8 should fix the first issue.

Modifying a lighting effect file seems to work for me. I modify the file, then go back to the main page, then click 'apply' which applies the modified lighting effect. This doesn't work for you?

**Comment by veronikazaglotova** [comment]
> This doesn't work for you?

For some reason, it works now. I didn't test the thing but I'll close the issue.
