### ISSUE TITLE
[Feature request] Export config from GUI to text file

### ISSUE THREAD

**Issue by veronikazaglotova** [pixeltris/GK6X#101]
I edited everything in the GUI and clicked save. But I have no text file! I wish I could have it. I wanted to change everything to what I need real fast with a mouse and then edit to change the default layer and what the P key does, but unfortunately the file is empty.

**Comment by pixeltris** [comment]
The web GUI has its own file system which is controlled via the web GUI JavaScript (it's the same file system that the official software uses). The GUI/non-GUI files aren't directly compatible.

It's possible to export the web GUI lighting effect files via the `gui_le` command. See https://github.com/pixeltris/GK6X/issues/62#issuecomment-670667390

As for the key mappings, there currently isn't any command to generate this from the web GUI. Something similar to `gui_le` would need to be implemented.

**Comment by pixeltris** [comment]
https://github.com/pixeltris/GK6X/commit/7c8b9cec9a22fd387acdf84fac31cb4ed248e4da This commit adds some rudimentary support for this via `gui_to_txt` which outputs the txt file to `UserData/XXXXXX_exported.txt`. It didn't test it much and lighting effect files wont auto export (you'd need to use `gui_le` first for them).

I wouldn't recommend using it, and there's no way of converting between back to a GUI format. The issue with attempting to do something like that is that the layouts differ so there will always be loss of data both ways.
