### ISSUE TITLE
Fn Layer doesn't seem to work on GK61

### ISSUE THREAD

**Issue by ksalanga** [pixeltris/GK6X#103]
I tried to write 
[FnLayer1]
Q:A

on the txt file in user Data
to test if FN+Q would type A, (btw im using the Right function on my keyboard), but it doesn't seem to be working.

Also, how do I switch layers? what's the function for that

**Comment by h3oCharles** [comment]
did you save, apply and set yourself to layer1?

**Comment by pixeltris** [comment]
Closing this as the mapping should definitely work on GK61. Ensure the mapping was applied as mentioned above, and ensure you're on Layer1 to test your mapping.
