### ISSUE TITLE
Support GK96S

### ISSUE THREAD

**Issue by qqldd** [pixeltris/GK6X#104]
Just got their latest GK96S, seems this software doesn't work with it. Is there an easy way to support it?

**Comment by pixeltris** [comment]
You might be able to copy one of the other 96 variants e.g. `SK96S RGB` https://github.com/pixeltris/GK6X/blob/master/Build/Data/device/modellist.json

You'd want to find your model id then duplicate the folder of `656801880`, then rename to the model id for your keyboard.

Or just wait until the official software adds support for your keyboard.

**Comment by pixeltris** [comment]
As mentioned repo follows the data files from the official software at http://www.jikedingzhi.com/downloadlist?driverID=41latest.

As GK96S is a mainline keyboard I assume the data files will become available at some point. I wont be manually adding data files to this repo for mainline keyboards as it will conflict with future data when it's officially supported.
