### ISSUE TITLE
Cannot assign different colors to layers automatically on GK68XS

### ISSUE THREAD

**Issue by wookash** [pixeltris/GK6X#105]
How do I assign different colors to layers automatically? In the GUI this option is disabled.. When I tried the config file in User Data folder (as per instructions) it only works on the base layer, switching to layer 1, 2, 3 does not change the lightning. When plugged, I can set the colors to the driver layer, but that's not what I want.

**Comment by pixeltris** [comment]
Only certain keyboards support different lighting for each layer. I think it's only the older GK6X boards which support it.
