### ISSUE TITLE
Aliases for some keyboard configurations

### ISSUE THREAD

**Issue by veronikazaglotova** [pixeltris/GK6X#108]
Sometimes the user wants to have the whole layer to be empty with some keys enabled for other things. Maybe make an alias for "make the whole layer empty"? Would be pretty good in my opinion. I didn't think of other aliases honestly.

**Comment by pixeltris** [comment]
Probably the easiest way to do this would be to create an internal `DriverValue` called `All`. Then the mapping would be something like this:

```
[Layer1]
All:Disabled
A:A
B:B
C:C
```

Some additional code would need to be added to mapping to check for the internal `All` value and set everything to the desired key at that point.

**Comment by pixeltris** [comment]
Implemented in https://github.com/pixeltris/GK6X/commit/81f62e3ad647b7d010ef0825ff90c172793b38d1 and can be used as described above.
