### ISSUE TITLE
GK61xs Arrow Key Remapping

### ISSUE THREAD

**Issue by kaiwen2times** [pixeltris/GK6X#109]
Great software for tinkers that want to customize their GK6x keyboards. I want to map the layer 1 Fn as right arrow so I can have the bottom right cluster keys as arrow keys while layer 1 is active. The README suggests that `You can reprogram the base layer and layers 1-3 (and the Fn keys). The 'driver' layer isn't supported. The firmware doesn't allow you to reprogram the Fn keys on the base layer`. So it sounds like it's possible to remap  Fn key in any of the layers. Could you provide an example txt file of how to remap Fn in layer 1 to right arrow key?

**Comment by willerbee** [comment]
i never was able to remap the fn key, it's the only key that can't be remapped. i think what this means..

> `You can reprogram the base layer and layers 1-3 (and the Fn keys). The 'driver' layer isn't supported. The firmware doesn't allow you to reprogram the Fn keys on the base layer`.

..is that you can remap the keys in the base layer and layers 1 to 3 (and the Fn layers for layer 1 to 3) except for the keys in Fn layer for the base layer.

**Comment by pixeltris** [comment]
It could probably be worded better in the README, but yes it behaves as @willerbee describes. None of the GK6X firmwares support moving the fn key.

To clarify; the following are all separate "sets" of keys which can be mapped in any way you see fit: Base, Layer1, Layer2, Layer3, FnLayer1, FnLayer2, FnLayer3. The only exception is that you can't move the fn key.

You can simulate something similar to an fn key by using `TempSwitchLayerBase`, `TempSwitchLayer1`, `TempSwitchLayer2`, `TempSwitchLayer3`. These temporarily switch to another layer for as long as you hold down the key. For example, the following will switch to Layer1 for the duration that `RShift` is held down.

```
[Base]
RShift:TempSwitchLayer1
```
