### ISSUE TITLE
key combination

### ISSUE THREAD

**Issue by ramestica** [pixeltris/GK6X#111]
Hi,

I just got a skyloong GK64 keyboard. I assumed that I should be able to assign shift+backspace (both keys pressed at the same time) to Insert. However, using GK6XPlus Driver GUI program, I could not figure out how to do it. At the bottom of the GUI screen there is something about configuring a key combination and I assumed that that's what I need to do, hence the title of my message here.

Then I came across GK6X. I installed under linux, and I can confirm that the software works for me by replacing CapsLock on Layer1, with LCtrl

But then I tried the following in the configuration file:

[Layer1]
CapsLock:LCtrl
LShift+Backspace:Insert

and I do not get the expected behavior for the lshift+backspace 'combination'.

I guess that I'm misunderstanding the ways a keyboard like this can actually be configured. Is there anyway to accomplish what I have described above?

Thanks,
 Rodrigo

ps: over the years I have used setxkbmap and xmodmap (linux) to tune the keyboard to my preference. I would like to finally get rid of that script by configuring the keyboard in firmware instead.

**Comment by pixeltris** [comment]
Unfortunately none of the firmwares support mapping keys in that way. You can map a single key to a combination, but not the other way around. The only exception to this is temporary layer switches. For example this can somewhat simulate what you're after:

```
[Base,Layer1,Layer2,FnLayer1,FnLayer2]
LShift:TempSwitchLayer3

[Layer3,FnLayer3]
Backspace:Insert
```

**Comment by ramestica** [comment]
oh! thanks for the clarification. And many thanks for the software tool you have developed.

The example above seems to require to switch to layer3 to insert using shift+backspace, and then back to my working layer. Is it that operation what you meat by simulation?

In any case, my experience is that whenever I'm trying to 'force' something that the system does not support, then, at the end, it will be on me to carry some degree of burden to keep the forced feature working. Better to accept the system as is, and live with it :-)

thanks, again.

**Comment by pixeltris** [comment]
Yes, the above example will stay in layer3 for the duration that LShift is held down. But yea unfortunately the firmware is quite limited which isn't super ideal for keyboards with fewer keys. The temporary switch layers are definitely useful in such cases though.
