### ISSUE TITLE
double function key

### ISSUE THREAD

**Issue by davidsu** [pixeltris/GK6X#113]
Hi, thanks for your amazing work!
I have a question ( this might not be the right place to ask it ). I'd like to have caps mapped to "control or escape" and return to "control or return". I suspect that my gk61 firmware won't allow for this. I'm really keen to having this on the keyboard ( as opposed to software on my OS ). Is there some way to get this working on my keyboard ( maybe some custom firmware )?
If not, do you know how I'd go about finding/building a keyboard with this functionality?

**Comment by davidsu** [comment]
I've been thinking that maybe this could be achieved with a macro, but looking more closely at it I'm in doubt.
The behaviour should be: 
 On control up:
    if less than 200ms passed since control down AND no other key was pressed while control down:
       send Escape
then just map capslock to control
looks like macros don't give me this level of control, am I right?

for completeness, if it were a macro, let caps be macro triggerer:
  On macro triggerer down:
     On other key:
        Press control
     On triggerer up:
        If no other key was pressed AND less than 200ms passed:
            send escape
        else:
           do nothing(well, release control)

**Comment by pixeltris** [comment]
This functionality isn't supported by the keyboards, and the macro functionality is too basic to achieve the above. You'll want to look for QMK keyboards for this type of functionality.
