### ISSUE TITLE
french accents

### ISSUE THREAD

**Issue by Marlababich** [pixeltris/GK6X#114]
Hello, I'm French and I wonder if there is a way for adding accented letter like é, è...?

**Comment by pixeltris** [comment]
I don't believe so, the key mappings are fairly basic. I think you'd need to use software mapping for that.

**Comment by Marlababich** [comment]
Okay, thank you...!

**Comment by Jonavin** [comment]
Just wanted to say I found a workaround for mapping any character and having it saved to the keyboard without requiring software like SharpKeys. Assuming the character you want is available via Alt Codes. For example, if you wanted e accent aigu é (alt code 0233) you can do this:

#/*----------------- sample --------------
#  character é
[Macro(FrenchEaccentAigu,0,RepeatXTimes,1)]
Down:LAlt
Press:NumPad0
Press:NumPad2
Press:NumPad3
Press:NumPad3

[Layer2]
### or whatever layer you want to program
E:Macro(FrenchEaccentAigu)

#----------------- sample --------------*/


I managed to do this to set up a bunch of math symbols and greek letters for Layer2 and used Capslock at my tempLayer2 activation.  It works really well so far but these Alt codes are specific to Windows. You'll have to program the equivalent Mac combos for those characters.

It would be better if it could just send any string.
