### ISSUE TITLE
[Feature request] Setting lighting with hex codes?

### ISSUE THREAD

**Issue by calmestwill** [pixeltris/GK6X#115]
I was wondering whether it would be possible to set the lighting of the keyboard using hex color codes. If the keyboard supports it, I presume that it would be as easy as specifying the hex code to set the lighting?

**Comment by pixeltris** [comment]
You can do that, though the file is still in json so it's a little verbose. Here's an example (this uses '0x' hex prefix but '#' also works):

https://github.com/pixeltris/GK6X/blob/master/Build/Data/lighting/WASD%20static.le

**Comment by calmestwill** [comment]
Thank you, works like a charm!
