### ISSUE TITLE
Remapping physical switches for different layout keycaps

### ISSUE THREAD

**Issue by jwefers** [pixeltris/GK6X#116]
First, thank you so much for proving this alternative driver - i had some trust issues with cinese software requiring admin permissions on my computer :D Be it for quality or danger of malware.

I was looking long and hard for a  german keyboard with around 65% and Bluetooth. Could not find any and settled for the GK64S.

Now i wonder: On a german keyboard, some keys cover differnt sets of physical switches than on the US layout. Could i buy a fitting set of german keycaps, put them on the GK and happily remap the keyboard accordingly?

E.G. LShift is a single physical switch, Enter is two switches but vertical. Is that possible to achieve using your software? I see a DriverValue array in the Key class which seems to me that it could be related to this? Would also be willing to write some C# code if you say hts theoretically possible.

**Comment by jwefers** [comment]
my hopes just got shattered when i removed the shift key and saw only a single actual switch

**Comment by pixeltris** [comment]
I think variants of some of the GK6X boards have spacebars with multiple switches, but those are fairly limited in the way you can map them. Unfortunately the mappings are quite lackluster in general for keyboards with fewer keys, really you need something like QMK for smaller boards.

**Comment by jwefers** [comment]
I need Ducky to just make a BT variant of the One 2 SF.  But the GK64 really has the perfect layout - arrow keys, Del, no space wasted on Rshift, rctrl etc.

Thanks for the reponse anyway ;)
