### ISSUE TITLE
GamaKay MK61 support

### ISSUE THREAD

**Issue by m-m-0-0** [pixeltris/GK6X#117]
Hello, I've recently bought a [GamaKay MK61](https://www.banggood.com/Gamakay-MK61-Wired-Mechanical-Keyboard-Gateron-Optical-Switch-Pudding-Keycaps-RGB-61-Keys-Hot-Swappable-Gaming-Keyboard-p-1797608.html?cur_warehouse=CN&ID=62878456290921), which is very similiar to the SK61 in appearance. 
Windows recognizes the keyboard as SK61L (which I can't find anything about online), but the software doesn't even try to connect to it.
It doesn't have its own software (yet?) and the gk6x one doesn't work.
this is the output of lsusb on linux:

Bus 001 Device 019: ID 1ea7:9018 SHARKOON Technologies GmbH SK61L

If anyone knows anything about it, then please share!

**Comment by pixeltris** [comment]
This program should try to handshake with it and tell you your model id, which you might already match up to something in the data files.

If it doesn't try to handshake maybe try looking at this line and where it's referenced to see if it needs to be tweaked https://github.com/pixeltris/GK6X/blob/9bd09b4a96fe26c01dad24a6f0fe73008e0509a7/GK6X/KeyboardDeviceManager.cs#L15

**Comment by m-m-0-0** [comment]
I've tried adding the pid to knownProducts, but the usb descriptor is different. There's no interface with report length 65, so it could mean it's using a different protocol, but that would be strange as the layout of the fn layer and most of the functions of the kb are basically the same as other clones (for example, the led modes are the same as the Kemove Snowfox).

**Comment by pixeltris** [comment]
I assume the report length is 64? You could try 64 and see how far it gets into the `Handshake` function. Though if uses different software it likely has its own protocol and sending invalid data to it could potentially cause issues.

**Comment by m-m-0-0** [comment]
this is the full descriptor: https://pastebin.com/YBp8bP09
biggest report length seems to be 16, nowhere close to 64-65. I've noticed interface 1 actually sends data about what lighting type you select and when you press the FN key, so that gives me hope that an actual software exists for this, just I guess it's not this one.
Thank you for your help!

**Comment by leosmartins** [comment]
Any update for this? My windows still recognizing the keyboard as SK61L, and the software newer version doesn`t work.

**Comment by pixeltris** [comment]
It looks like official software has appeared on [banggood](https://www.banggood.com/Gamakay-MK61-Wired-Mechanical-Keyboard-Gateron-Optical-Switch-Pudding-Keycaps-RGB-61-Keys-Hot-Swappable-Gaming-Keyboard-p-1797608.html) which has links to [this](https://drive.google.com/file/d/1Puj6QBxviU98ZO2jmZCFtyoEJr1BJvT_/view?usp=sharing) and [this](https://drive.google.com/file/d/1drczjZ0ifAJIffam4W9NM_Esf7EEEf5n/view?usp=sharing).

I downloaded one and the software is definitely different to the GK6X boards. So unfortunately I can't add support for it.
