### ISSUE TITLE
How to add Fn2 key

### ISSUE THREAD

**Issue by JonasJR** [pixeltris/GK6X#122]
First of all, Thank you so much for a great tool! 
I'm currently writing on my GK64XS and have managed to apply most of the things that I need for a Swedish keyboard layout. How ever, in my attempts on making this the perfect keyboard I found that I need to have separate remap the bluetooth or add another Fn2 key. 
I have the | and <> located on Fn+Z,X,C to be as close to a Nordic keyboard layout as possible. That means that I have managed to overwrite the bluetooth on Layer1 (I need to first go in to Fn+W to activate that before I can use | <>) . BUT! After these signs often comes a space, and if I have not released the Fn button that will bring me in to bluetooth mode (I believe?) and I have to do the Fn+Space again and then Fn+W to get to the layer. 
My thought is to add a Fn2 button (I have installed the divided space now so figured I could put that on Space_4). But how do I add another Fn2 that is not triggering the other Fn layer?
Do you have any suggestions for this?

**Comment by pixeltris** [comment]
Those split spacebar keys have a specific way in which they function. If you tap them they will be a space key, if you hold them they will enter into one of the layers based on how the key is mapped (`TempSwitchLayer1`, `TempSwitchLayer2`, `TempSwitchLayer3`).

You'll probably want to be looking at those temp layer switches. You can assign those temp switch layers to any key to somewhat emulate an alternative Fn key.

**Comment by JonasJR** [comment]
Ah! Thank you! Worked like a charm!
For next one who would like to do the same thing, this is my datafile:
````
# Map keys:
# Add AltGr 
[Base,Layer1,Layer2,Layer3,FnBase,FnLayer1,FnLayer2,FnLayer3]
Menu:RAlt
Space_4:TempSwitchLayer3

# Add pipe and greater than...
[Layer3]
Z:Macro(Pipe)
X:Macro(Great)
C:Macro(Less)

# Macros
[Macro(Pipe)]
Press:RAlt+AltBackslash
[Macro(Less)]
Press:LShift+AltBackslash
[Macro(Great)]
Press:AltBackslash
````
