### ISSUE TITLE
Disabling CapsLock

### ISSUE THREAD

**Issue by davidcortesortuno** [pixeltris/GK6X#124]
Hi, I have a GK61 and I'm trying to disable CapsLock, which works but then mapping other combinations do not have any effect, my config file is this one

```
# This will disable Caps on layer1
[Layer1]
CapsLock:Disabled

# Map Fn+M (Del) to CapsLock + <--
[FnLayer1]
M:CapsLock+Backspace
```

Am I missing something?

**Comment by pixeltris** [comment]
You can only map a single key to another single key. The only exception to this is modifier keys. For example you can map `M` to `CapsLock+LCtrl`. But you can't map it to `CapsLock+Backspace`.

If you want to do `CapsLock+Backspace` you'll have to utilize macros. Something like this would do it I think:

```
[Macro(MyMacro1)]
Down:CapsLock
Down:Backspace
Up:CapsLock
Up:Backspace

[FnLayer1]
M:Macro(MyMacro1)
```

**Comment by davidcortesortuno** [comment]
Ah I see, thanks. But what if I want `CapsLock+Backspace` to work as `Del` (which works in the GK61 as `Fn+M`)? I guess it is not possible, as it is a combination of keys

**Comment by Jonavin** [comment]
This is how I would do it



#Make Capslock TempLayer2, Use Fn Capslock to Capslock
[Base,Layer1,Layer3]
CapsLock:TempSwitchLayer2

[Layer2]
Backspace:Del

**Comment by davidcortesortuno** [comment]
Awesome, it's super useful, as I can now map the arrow keys to HJKL in Layer 2 :)
