### ISSUE TITLE
This site can’t be reached when running GUI on linux

### ISSUE THREAD

**Issue by ProgrammingMyLife** [pixeltris/GK6X#126]
I am trying to run the driver on Arch Linux.

I cloned the latest release and tried 

`sudo mono GK6X.exe`

which gave me

`Connected to device`

However when going to http://localhost:6464/#/, it said refused to connect

**Comment by pixeltris** [comment]
I assume you typed the `gui` command? That starts up the server. I can't think of a reason why your browser wouldn't be able to connect other than maybe some conflicting network config.

**Comment by pixeltris** [comment]
Probably the same problem as https://github.com/pixeltris/GK6X/issues/38

**Comment by pixeltris** [comment]
Closing in favor of #38
