### ISSUE TITLE
Manual for all possible Key mappings

### ISSUE THREAD

**Issue by tcoro** [pixeltris/GK6X#127]
Really like this project, and only wanted to map UpArrow and DownArrow to some Media related keys, like play/pause, next, previous.

Where do I find the names for these keys?
```dumpkeys``` only shows base layer (gk68xs)

**Comment by pixeltris** [comment]
The key values can be found here https://github.com/pixeltris/GK6X/blob/6ef1a8012beeb5fdd891906a6569bd0fc3209d75/GK6X/KeyValues.cs#L269

ctrl+f for `media`. Arrows are `Left`, `Right`, `Up`, `Down`.

**Comment by tcoro** [comment]
thank you very much!
I just had it in my mind that I found that earlier, but didnt found it again, sorry :)
