### ISSUE TITLE
Purchased sk61 trouble downloading software 

### ISSUE THREAD

**Issue by ibrar2002s** [pixeltris/GK6X#128]
im struggling to open the software to change the rgb and reconfigure the bindings on my mac, i followed the online manual and it says the file does not exist when in the terminal. Thanks 
<img width="722" alt="Screenshot 2021-03-29 at 19 32 52" src="https://user-images.githubusercontent.com/81586984/112884559-8ccbf300-90c7-11eb-9720-b011045ad5ae.png">
mac terminal:

Ibrars-MBP:~  cd Desktop
Ibrars-MBP:Desktop  cd GK6X-v1.13-GUI/
Ibrars-MBP:GK6X-v1.13-GUI  mono GK6X-v.1.13-GUI
Cannot open assembly 'GK6X-v.1.13-GUI': No such file or directory.
Ibrars-MBP:GK6X-v1.13-GUI  mono GK6X.exe
Connected to device 'SK61S-RGB' model:656801822 fw:v1.14
GUI
Started web GUI server at http://localhost:6464
The file /Users/ibrariq/Desktop/GK6X-v1.13-GUI/open http:/localhost:6464 does not exist.

thats what it says ^^^^^

**Comment by pixeltris** [comment]
That comes from https://github.com/pixeltris/GK6X/blob/6ef1a8012beeb5fdd891906a6569bd0fc3209d75/GK6X/WebGUI.cs#L51

Essentially it's failing to launch the web browser. But you should be able to manually navigate to `http:/localhost:6464`.

There's an official Mac program available which might be better suited to your needs http://www.jikedingzhi.com/downloadlist?driverID=90 I need to add the link to the README but I haven't got around to it yet.

**Comment by pixeltris** [comment]
I'll look at improving the `open` invocation at some point. But otherwise should be behaving correctly so I'll close this.
