### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by hbsa202** [pixeltris/GK6X#13]
Thanks so much for putting this together! I have a GK61 and love the board, but am paranoid of installing the stock software, especially with the thing having a mic for what are dubious functional reasons IMO. Since it seems like you've been pretty deep in the code, have you seen any security issues in the firmware or downloadable configuration software? If so, does your software address them?  I'm not an experienced developer so would very much appreciate any insight you may have :)

**Comment by pixeltris** [comment]
From what I can tell the keyboard doesn't have any functionality to send mic data from the keyboard to the PC.

You can read an annotation of the firmware by @wgwoods here https://github.com/wgwoods/gk64-python/blob/master/disasm/BBD8.disasm

From reverse engineering the official software with IDA I couldn't see any components which raised any red flags. I wouldn't have any worries using the official software. My project is simply an alternative to the official, my goals with it were to see what the keyboard protocol supports. There are a couple of very minor artificial key mapping limitations in the official software, but by and large the official software should do what you want and I'd recommend using it.

**Comment by hbsa202** [comment]
This is massively helpful - thanks so much for the time and information.
