### ISSUE TITLE
Split space bar 

### ISSUE THREAD

**Issue by simpleas123** [pixeltris/GK6X#130]
Hi 

Assuming I'm on layer 1 (where FN keys are reprogrammable) is it possible to remap the right space bar to toggle to layer 2? i.e. I don't want to hold the left space bar to access the next layer, just a tap.

Thanks!

**Comment by pixeltris** [comment]
The way the split spacebar keys are handled is hard coded into the firmware.

If you tap the spacebar it'll output a space key. If you hold down the spacebar it can enter to an another layer for the duration that you hold down the spacebar key (i.e. you can enter into layer 2).

I don't think you can make it change layers on a single tap.

**Comment by simpleas123** [comment]
The official firmware lets you change one of the spacebars to a backspace button. It also lets you map a keyboard combination to it too?

Would I not be able to change the switch layer combo on layer 1 to say, CTRL + E and then change the keyboard combo on the space bar to that?

**Comment by pixeltris** [comment]
Some of the different keyboards might be advertised in different ways and may have slightly different ways in which they work firmware wise.

Ultimately those spacebar keys are just additional keys which can be mapped, so I'd just suggest experimenting and seeing what works best for you.

Typically the mapping would look something like this:

```
[FnLayer1]
Space_2:TempSwitchLayer3
```

I don't know what you mean by `CTRL+E`. It isn't possible to map `CTRL+E` as its own combination. You can only do the opposite. E.g:

```
# This ISN'T valid (can't map FROM a key combination)
[FnLayer1]
LCtrl+E:Backspace

# This IS valid (can map TO a key combination)
[FnLayer1]
E:LCtrl+Backspace
```

**Comment by simpleas123** [comment]
_**The workaround to something like this is making LCtrl switch to a different layer, and put your desired mapping for E on the target layer.**_

This is exactly what I want to do with the split space bar instead of LCtrl. So I would switch layer by pressing the second space bar rather than LCtrl. 

The keyboard is the GK68XS which, in the manual, shows you can remap the second space bar to backspace (or any other key). 

This board changes to layer 2 by pressing FN+ E however using the stock software you can't remap FN in any layers. 

So ideally, using GK6X, I would change the switch layer button (in layer 1, not the base) to the split spacebar. Is that not possible?

**Comment by pixeltris** [comment]
Yes, that was the first example I mentioned:

```
[FnLayer1]
Space_2:TempSwitchLayer3
```

That will switch to layer 3 for the duration that the split space key is held down (you may need to verify the actual key name, duplicate key names such as `Space_2` aren't always consistent).

**Comment by simpleas123** [comment]
Thank you. if I cannot map this to the space bar I will use Z.

**Comment by Jonavin** [comment]
The spacebar has space use on these boards. You do a layer toggle button with any other key except space bars and Fn key.  So I did a test with the Capslock as a Layer2 Toggle and this works perfectly fine. You do have to include Layer2 in the definition so you can toggle back. 

This works with any other key to toggle to Layer2.  Replace with other layers if you want to switch to those

[Base,Layer1,Layer2,Layer3]
CapsLock:Layer2Button
