### ISSUE TITLE
Key value for AltGr key?

### ISSUE THREAD

**Issue by RabidTunes** [pixeltris/GK6X#134]
Is there a key value for the AltGr key used in ISO keyboards? So i can remap any key to be AltGr key

**Comment by pixeltris** [comment]
I haven't identified that key, but it could potentially exist. The keys I've found are here https://github.com/pixeltris/GK6X/blob/7b6cb5a7e15883cfd55dd3ef85c231f8db1131e3/GK6X/KeyValues.cs#L269

Maybe if there's a keyboard which has that key by default, you could identify the key value that way.

**Comment by RabidTunes** [comment]
Thanks, you are right. Mapping the key I wanted to be AltGr to `RAlt` made it work. I already saw that value in the list, but I didn't try that before because I assumed it would behave the same as `LAlt`

Maybe you could add a small comment above line 376 (just before RAlt) like this
```/// <summary>
/// Some users report that RAlt behaves like AltGr in ISO layouts
/// </summary>```

Thanks again for your help!
