### ISSUE TITLE
Mapping lighting fails silently on Linux 

### ISSUE THREAD

**Issue by dxbednarczyk** [pixeltris/GK6X#139]
I'm using the latest version of Manjaro Linux, and after compiling with `mono` my data file for the GK61XS RGB (filename is 656801835.txt) has one line:

`[Lighting(Gradual,Base)]﻿`

After mapping this to the keyboard, it says "Done" and when I switch to the base layer by pressing FN + Q, there are no lighting effects.

![image](https://user-images.githubusercontent.com/54457902/117099126-fded6e80-ad35-11eb-90b4-46f0c96b2167.png)

**Comment by pixeltris** [comment]
Are you in "reactive" lighting effect mode? There are two lighting effect modes. One which is the custom defined lighting effects. And the other is "reactive" lighting effects which are hard coded into the firmware.

Assuming you're in the custom lighting effect mode, it's hard to tell what's going wrong. There probably should be some logging added which at least tells you it sent the expected data to the keyboard. However, there isn't really a way to determine reasons of failure on the keyboard side, as the firmware never sends detailed info of this back through the protocol.

**Comment by vanarok** [comment]
> Я использую последнюю версию Manjaro Linux, и после компиляции с `mono`мой файл данных для GK61XS RGB (имя файла 656801835.txt) имеет одну строку:
> 
> `[Lighting(Gradual,Base)]﻿`
> 
> После сопоставления с клавиатурой появляется сообщение «Готово», и когда я переключаюсь на базовый слой, нажимая FN + Q, световых эффектов нет.
> 
> ![image](https://user-images.githubusercontent.com/54457902/117099126-fded6e80-ad35-11eb-90b4-46f0c96b2167.png)

FN + Q is the driver layer, not the base layer.
