### ISSUE TITLE
how to even start the program

### ISSUE THREAD

**Issue by Croi100** [pixeltris/GK6X#14]

**Comment by satanworker** [comment]
lol! I have the same question :D

**Comment by pixeltris** [comment]
It's just a command like program (no GUI). Once the command line is open it will attempt to connect to your keyboard, at which point you can use commands such as 'map'. See the README.

If the console just stays blank then it's likely failing to detect any keyboard. Data files were recently updated so it might 'just work' now.

Feel free to reopen if this issue persists.
