### ISSUE TITLE
Decrypting .le files from the official software

### ISSUE THREAD

**Issue by oplexz** [pixeltris/GK6X#140]
You [mentioned](https://github.com/pixeltris/GK6X/issues/62#issuecomment-670599954) that the effect files are encrypted with a "basic form of encryption". Then I assume it's possible to encrypt them back into the state that the official software supports?
Could you please explain the alghorithm, or pinpoint where that happens in your code?

**Comment by pixeltris** [comment]
https://github.com/pixeltris/GK6X/blob/7b6cb5a7e15883cfd55dd3ef85c231f8db1131e3/GK6X/CMFile.cs#L166

There are a few references to that function in the web gui code. This one writes lighting data for the web gui:

https://github.com/pixeltris/GK6X/blob/7b6cb5a7e15883cfd55dd3ef85c231f8db1131e3/GK6X/WebGUI.cs#L729

**Comment by oplexz** [comment]
It took me a while, but I figured it out. Thanks!
