### ISSUE TITLE
GK61 having RGB issues

### ISSUE THREAD

**Issue by Ene493** [pixeltris/GK6X#142]
So! First the blue and green from "M" has burnt out, it doesnt light up anymore if it isnt red. Now, my caps, "R", "8", ";" and "menu" have a slight green color even when everything else is blacked out. Can someone help me with this?

**Comment by pixeltris** [comment]
Unfortunately that sounds like a hardware issue and I'd recommend you contact the keyboard supplier.

**Comment by veronikazaglotova** [comment]
When you connect the keyboard to the computer, it should light up all the keys with white (or in my case, white-purple-blue gradient because the lense seems to be weird). Do all the keys light up normally? If not, it's a hardware issue
