### ISSUE TITLE
[Linux] Fix browser resize window for the gui

### ISSUE THREAD

**Issue by didli** [pixeltris/GK6X#144]
First, thank you for making this software available for Linux users. I've just received a GK68XS and while I don't understand everything for now I'm quite enjoying the tweaks I've tried this far. Thank you.

Now for the issue : I run the gui with Vivaldi (chrome based)/Firefox and got the same result with it :

On both, elements of the gui cover each other. For example in a maximized browser window, in Configuration, I can't click on the layer buttons since elements like 'Primary', 'ESC' etc were on top of them. Meaning I couldn't get anywhere close to edit/apply a lighting until I resized my browser window to try to separate each element.

Is there already a fix or a workaround ? If not, maybe it could help first users like me to get this mentionned somewhere.

Anyway, Thank you again for GK6X.

**Comment by pixeltris** [comment]
It's an aspect ratio issue (unless I'm mistaken about what you're talking about). The best way to overcome this is to pop out the tab manually resize it to the correct aspect ratio. See https://github.com/pixeltris/GK6X/issues/65

**Comment by didli** [comment]
Thank you. You're not mistaken, that's it. 
That's almost what I'm doing for now : I'm using a specific browser I don't run often (Midori) which should lessen the chance to mess up my usual browsers. Maybe this could serve as a solution ? Running the GUI from a super tiny browser of sort that would be packed with GK6X ?

**Comment by pixeltris** [comment]
I've played around with that idea, but all of the embedded browsers for C# are extremely large. Maybe one of the lightweight webapp bundlers might work, but there would most likely be quite a lot of work required to get the C# code hooked up.

Another option might be to rebundle the official Mac software as that uses more of a raw webapp approach (as opposed to the Windows version which has more native C++ components). The core of that can be found under `GK6X Mac App-1.0.0.5.dmg\GK6+ Mac App-1.0.0.5\GK6+.app\Contents\Resources\app\`.

As I don't actually use the GUI it's all a bit too much work to be honest!

**Comment by pixeltris** [comment]
Closing this as mentioned I don't really have any plans of doing GUI embedding due to the size issues.

https://github.com/konsumer/node-gk6x is one to watch.
