### ISSUE TITLE
Example of disabling all or multiple keys on layer

### ISSUE THREAD

**Issue by MikaelElkiaer** [pixeltris/GK6X#145]
Do you have an example of using the `KeyValues.Key.DriverValueArray`?

For a specific layer, I would like to disable all keys except the ones that I explicitly map. It seems cumbersome to set all values to Disabled, so perhaps there's another way. :)

**Comment by pixeltris** [comment]
Unfortunately this isn't implemented yet ref https://github.com/pixeltris/GK6X/issues/108

Something would need to be added just before this line:

https://github.com/pixeltris/GK6X/blob/495bd783830fc6c607ab42aeb8852a868992a44e/GK6X/Program.cs#L564

I think it would go something like:

```
uint allValue;
if (userDataLayer.Keys.ContainsKey("All", out allValue))
{
    for (int j = 0; j < driverValues.Length; j++)
    {
        driverValues[j] = allValue;
    }
}
```

It might be saner to check if the key exists like the loop below, but it might not matter. Also `All` would need to be added to the `DriverValue` enum with a dummy value.

**Comment by pixeltris** [comment]
I don't know why I didn't just code it rather than write the comment, so there we go! https://github.com/pixeltris/GK6X/commit/81f62e3ad647b7d010ef0825ff90c172793b38d1 should implement that, used as mentioned above.

**Comment by MikaelElkiaer** [comment]
> I don't know why I didn't just code it rather than write the comment, so there we go! [81f62e3](https://github.com/pixeltris/GK6X/commit/81f62e3ad647b7d010ef0825ff90c172793b38d1) should implement that, used as mentioned above.

Thanks for answering the question - in both English and C#. ;)
