### ISSUE TITLE
Linux can't open web GUI

### ISSUE THREAD

**Issue by Tsumuri-u** [pixeltris/GK6X#146]
![image](https://user-images.githubusercontent.com/68445671/120055686-8df89e00-bfec-11eb-838b-59d0c7939808.png)

Using the latest GUI release 1.15 and running it as sudo, it successfully finds my device but can't open the GUI.

When running it as non-sudo with WINE, the web GUI opens but doesn't recognize my device.

**Comment by pixeltris** [comment]
That message `xdg-open file 'open http://localhost:6464' does not exist` just means that it failed to try and launch your web browser at that url. You should be able to just go to that url manually in your web browser.

**Comment by Tsumuri-u** [comment]
Works, thanks!
