### ISSUE TITLE
Can't map keys, everything connects

### ISSUE THREAD

**Issue by morovis** [pixeltris/GK6X#147]
Hello, excellent job on the software by the way I can't believe the official one doesn't support base layer mapping which is done. Anyway, I haven't been able to get it working, when I > map [file].txt it outputs DONE but nothing changes on the KB when I dumpkeys again. I don't know what it could be really since the software connects to my kb and everything seems to be properly connected. 

Maybe this info is useful whenever the [model_number].txt file is created, it comes up as empty. 
I just want my useless menu button mapped to RCtrl on all layers, that's all I want out of life lmao. 

![Screenshot 2021-06-02 091533](https://user-images.githubusercontent.com/85072384/120486501-f7203e80-c369-11eb-88f6-5ed5ac14632f.png)

I would appreciate the help, thank you

**Comment by pixeltris** [comment]
I should probably remove / rename / or document what dumpkeys actually does. It just lists the visual name to the code name (i.e. to map '1', you need to use 'D1').

Yea, the mapping file will be empty to start with as there aren't any mappings.

Could you paste your contents of your mapping file and I'll take a look?

**Comment by morovis** [comment]
Oh ! I understand now, well that's even more useful, I was looking in the source code for that. I thought those were a dump of my current mappings. 

# Map Menu as RCtrl on all layers
[Base,Layer1,Layer3,FnLayer1,FnLayer2,FnLayer3]
Menu:RCtrl

[Reading your message again, based on the dump text, shouldn't it be App instead of Menu ?] 

That is my whole mapping file, I just want to do that as my main (and only)  issue with this kb is that key since I prefer CTRL. If I get that working I'll definitely tinker around some more though. 

Thanks a lot for the fast answer by the way ! awesome.

**Comment by pixeltris** [comment]
The `Menu` key is this key https://en.wikipedia.org/wiki/Menu_key

If you're after the "Windows" key https://en.wikipedia.org/wiki/Windows_key you'll want to use `LWin` or `RWin`.

**Comment by morovis** [comment]
Exactly, I'm trying to change that default "Menu" key thats on my keyboard to LCtrl or RCtrl, i've saved that text I pasted on my messaage earlier as keys.txt and on the terminal i'd type 

map keys.txt (Inside the same directory of course) 
Done 

and then nothing changes on my kb, the default menu key keeps mapped as menu and not Ctrl like I  want to. Is my syntax wrong or something ? I have also tried 

map Menu:LCtrl 
Done 
Map Menu:RCtrl 
Done 

I feel like i'm doing something wrong or it's something simple I'm missing haha

**Comment by pixeltris** [comment]
You'll want to use the txt file it generated earlier (in your case `656801841.txt`). And just type `map` without any additional arguments.

There is a way to use a custom txt file, but probably best to just start with the generated one until you can get it working.

**Comment by morovis** [comment]
It worked! Thank you so much
