### ISSUE TITLE
Couldn't find data path

### ISSUE THREAD

**Issue by armandeeps** [pixeltris/GK6X#151]
Launching the .exe with GK61 not launching a CLI or terminal and leaves the following message in KBLog.txt
`[20:42:44.2179614] Connected to device 'GK61X RGB' model:656801837 fw:v1.19
[20:42:44.2299555] Couldn't find data path
[20:43:14.2548832] Disconnected from device 'GK61X RGB'`

**Comment by pixeltris** [comment]
Strange it should only look for the data path if running in GUI mode.

**Comment by pixeltris** [comment]
I'm going to go ahead and assume you were running `GK6X.exe /gui` without the data files for the GUI. Going to close this. If this isn't the case, feel free to reopen this issue.
