### ISSUE TITLE
Keyboard GS66 gives array out of bounds error in KeyboardState.SetupDriverKeySetBuffer

### ISSUE THREAD

**Issue by hnridder** [pixeltris/GK6X#152]
GK6X fails for the GS66 keyboard, in my case the Epomaker GS66 AB Redhat SIKAKEYB, with an array index out of bounds exception in KeyboardState.SetupDriverKeySetBuffer at the line

    driverKeySetArray[index] = (uint)driverValue;

The keyboard is identified correctly as
Model id 656801867 firmware id 0x94218910 v1.16
with bufferSizeA x bufferSizeB 14x8 = 112
However, possibly unusual, the maximum LogicCode is 110, indeed less than 112, but the maximum Index is 117 which is too high for the array. Furthermore, not all Index-es are used, so allocating state.KeySet based on the number of indices doesn't work either. Simply hardcoding the size of state.KeySet as 128 solves the problem and seems to have no ill side-effects. 117 is currently the highes Index in Data/device

If you let me know what the proper solution is, I can implement it and create a pull request, if desired.

**Comment by pixeltris** [comment]
Some very weird ending values there, I assume they were left in by mistake and the official software has no problems with the additional data.

```
112 - 0x02002A00 - Backspace
113 - 0x02002800 - Enter
114 - 0x02002A00 - Backspace
115 - 0x02002800 - Enter
116 - 0x0A010001 - A macro
117 - 0x0A010001 - A macro
```

https://github.com/pixeltris/GK6X/blob/6ef1a8012beeb5fdd891906a6569bd0fc3209d75/GK6X/KeyboardState.cs#L200

A simple fix would be to change that line to the following which would stop invalid indices from being accessed.

`if (Json.TryGetValue(keySet, "Index", out index) && index < driverKeySetArray.Length &&`

**Comment by hnridder** [comment]
That fix works.
