### ISSUE TITLE
Does this work with Sk68S?

### ISSUE THREAD

**Issue by Yash-Garg** [pixeltris/GK6X#153]
Couldn't see a supported keyboards list or something so would be helpful if anyone can tell!

**Comment by pixeltris** [comment]
Looks like there are data files for it, so it should work.

https://github.com/pixeltris/GK6X/blob/0489a02c5ae1a207ff880e06675a48e83b40a3da/Build/Data/device/modellist.json#L717-L720

**Comment by Yash-Garg** [comment]
> Looks like there are data files for it, so it should work.
> 
> https://github.com/pixeltris/GK6X/blob/0489a02c5ae1a207ff880e06675a48e83b40a3da/Build/Data/device/modellist.json#L717-L720

Ah, Thank You!
