### ISSUE TITLE
Remapping fails silently on Arch Linux.

### ISSUE THREAD

**Issue by baduhai** [pixeltris/GK6X#156]
I've tried using your provided package, compiling it myself and using the AUR package none of them work. The program detects the keyboard and is able to dumpkeys and it claims to map, but doesn't map. This is the output of `sudo mono GK6X.exe /map 656801825.txt`:

```
[sudo] password for william: 
Filename: 656801825.txt
Connected to device 'SK64 RGB' model:656801886 fw:v1.35
Done
Disconnected from device 'SK64 RGB'
```

and this is what I'm trying to map:

```
[Base,Layer1,Layer3,FnLayer1,FnLayer2,FnLayer3]
Menu:RAlt

[Base,Layer1,Layer3,FnLayer1,FnLayer2,FnLayer3]
RShift:Delete

[Base,Layer1,Layer3,FnLayer1,FnLayer2,FnLayer3]
Delete:LShift
```

**Comment by pixeltris** [comment]
Possibly related to https://github.com/pixeltris/GK6X/issues/139

I haven't tested Linux in a while. Maybe somethings broke there. Unfortunately failures will always be silent. I could potentially detect failures, but it wouldn't actually provide any useful info.

**Comment by baduhai** [comment]
Is there any way I can provide you more info so we can trouble shoot this?

**Comment by baduhai** [comment]
I tried version 1.14 instead and that seems to have worked.

**Comment by pixeltris** [comment]
Weird, maybe there's a bug on this line with SK64

https://github.com/pixeltris/GK6X/compare/GK6X-v1.15...master#diff-94cb6a63521a3aa8ff05c2f5cf3d65e6772c6d652e321f95f458231ece8cd0f7L200

**Comment by aakashhemadri** [comment]
@baduhai I can help but notice that you are using 656801825.txt as the map input file while your device model 656801886. Not that the difference matters as long as the the file is legal for SK64. I'd suggest using /dumpkeys and modifiying that file to the changes in your 656801825.txt.

**Comment by baduhai** [comment]
I'll be honest, I don't remember what I did, but I did eventually fix this. Closing.
