### ISSUE TITLE
[feature request] documentation, tutorial or script to compile on linux

### ISSUE THREAD

**Issue by iapicca** [pixeltris/GK6X#158]
Hello,
is there any step by step documentation or tutorial (or even better a script)
to compile this software on linux?

Thank you

**Comment by pixeltris** [comment]
Unfortunately not super comprehensive instructions. It's something I've needed to address but haven't got around to. This issue describes the steps https://github.com/pixeltris/GK6X/issues/4

**Comment by iapicca** [comment]
also duplicate of https://github.com/pixeltris/GK6X/issues/118
sorry about that
