### ISSUE TITLE
Support for X-Bows keyboards

### ISSUE THREAD

**Issue by bemoody** [pixeltris/GK6X#16]
Thank you for providing this tool!

The X-Bows Knight keyboard (https://x-bows.com/) uses the same protocol, VID/PID, and presumably very similar firmware to the GK6X.

Windows drivers and firmware are available at https://x-bows.com/pages/software and might be of some interest.

Using the following patch, I'm able to communicate with the keyboard and remap most of the keys:
```
diff --git a/Build/Data/device/655491165/data/keymap.js b/Build/Data/device/656801808/data/keymap.js
similarity index 100%
copy from Build/Data/device/655491165/data/keymap.js
copy to Build/Data/device/656801808/data/keymap.js
diff --git a/Build/Data/device/modellist.json b/Build/Data/device/modellist.json
index 2bc006d..f8fd0af 100644
--- a/Build/Data/device/modellist.json
+++ b/Build/Data/device/modellist.json
@@ -105,4 +105,10 @@
 	"FWID": "0x90206412",
 	"Name": "GK64S RGB经典款",
 	"LEType": "0"
-}]
\ No newline at end of file
+},
+{
+	"ModelID": 656801808,
+	"FWID": "0x90216820",
+	"Name": "X-Bows",
+	"LEType": "0"
+}]
```

All of the "normal" keys work:
* Esc F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 Delete PrintScreen
* BackTick D1 D2 D3 D4 D5 D6 D7 D8 D9 D0 Subtract Add Backspace
* Tab Q W E R T Y U I O P OpenSquareBrace CloseSquareBrace Backslash PageUp
* CapsLock A S D F G H J K L Semicolon Quotes Enter PageDown
* LShift Z X C V V N M Comma Period Slash RShift
* LCtrl LWin LAlt RAlt RCtrl
* Left Up Down Right
* Space is the left space key.

These five special keys don't work:
* Right space
* Middle backspace
* Middle enter
* Middle control
* Middle shift

In addition, Fn seemingly can't be remapped, but I gather that's expected.

Note that by default:
* Right space generates the same X11 keycode (and presumably the same USB keycode) as left space.
* Middle backspace generates the same keycode as upper-right backspace.
* Middle enter generates the same keycode as right enter.
* Middle control generates the same keycode as right control.
* Middle shift generates the same keycode as right shift.
However, using GK6X to remap Space/Backspace/Enter/RCtrl/RShift does not affect the above five keys, so presumably each of them has a distinct internal keycode that can be remapped independently.

I am a bit baffled by all of the different model-specific configuration files (though it seems like keymap.js is the only one that matters?) not to mention KeyValues.cs and keys.json.

How can I determine what internal keycodes correspond to the missing keys, and which files do I need to edit in order to assign the correct labels to the physical keys?

**Comment by pixeltris** [comment]
I assume their software is a customized version of the GK6XPlus software? If so you should be able to extract the .js files from it.

I have been meaning to write a tool which can determine the keys on the keyboard, but it's a little bit tricky. The keyboard doesn't ever announce to the PC which keys are where, but I think it's somewhat possible by using macros in the 'driver' mode via the key callbacks.

I think keys.json in the official software is used to actually create that UI element where it lists all of the available keys at the bottom of the screen. That file is useful to build a list of keys and their names such as '-', '=', '/', 'A', etc.

keymap.js is the main thing that matters when defining a new keyboard. 'LogicCode' states where a key is in the firmware of the keyboard. 'LocationCode' is where the key is visibly for displaying in the UI (I'm not sure it matters so much what these values are in each individual keymap.js, so long as they are unique).

profile.json files are used to state the default layout of the keyboard. These are important to know what the default layout of the keyboard should be. If these aren't defined it wont be possible to know how to reset the keys to their default values. 'DriverValue' is what defines the actual value of each key, where 'Index' matches up to the 'LogicCode' defines in keymap.js

So yea... it's a little bit convoluted, but this is all stuff defined in the official software, so you should be able to extract it from the official software if available.

**Comment by bemoody** [comment]
Thanks for this helpful explanation.  I've done some digging and discovered a bit more.

I was able to unpack the Windows driver package using "innoextract".  It contains the following files, among others:

app/CMSEngine/driver/device/modellist.json
app/CMSEngine/driver/device/656801808/config.json
app/CMSEngine/driver/device/656801808/data/keymap.js
app/CMSEngine/driver/device/656801808/data/profile.json
app/CMSEngine/driver/device/656801808/data/profile_offline_1.json
app/CMSEngine/driver/device/656801808/data/profile_offline_2.json
app/CMSEngine/driver/device/656801808/data/profile_offline_3.json
app/CMSEngine/driver/device/656801808/data/profile_offline_std.json
app/CMSEngine/driver/device/656801808/data/profile_online_1.json

It also contains device files for all of the following models:

655491180
655491190
655491229
655491231
655491232
655491233
655491237
655491244
656801807
656801808
656801809
656801827
656801828
656801829
656801831
656801832

There is no keys.json.  There is app/CMSEngine/driver/res/data/keyset/allkeys.json, which seems similar, but it only contains LogicCodes going up to 111.

The special keys are defined in keymap.js, but the labels are a bit screwy:
- LogicCode 112 has KeyName = "Delete" and Show = "Del"
- LogicCode 113 has KeyName = "Return" and Show = "Enter"
- LogicCode 114 has KeyName = "Mid Ctrl" and Show = "Ctrl"
- LogicCode 115 has KeyName = "Left Shift" and Show = "Shift"
- LogicCode 116 has KeyName = "Right Backspace" and Show = "Space"

If I simply drop modellist.json and the 656801808 directory into Build/Data/device/, then "dumpkeys" displays a list of keys.

(The list is grouped into slightly odd "rows" since the physical keys aren't in a line.  But that's not a major concern.)

However, this list shows each of the special keys as 4294967295:
```
--------
Delete = 4294967295
--------
...
--------
Return = 4294967295
--------
...
--------
Space = Space
Right Backspace = 4294967295
--------
Mid Ctrl = 4294967295
Left Shift = 4294967295
```

In order for these keys to be recognized and to be remappable, I also have to add entries for LogicCode 112 through 116 to keys.json.  However, this requires specifying a DriverValue for each LogicCode.

If I use the DriverValues from profile.json:
```
{"LogicCode": 112, "DriverValue": "0x02002A00"}, // Backspace
{"LogicCode": 113, "DriverValue": "0x02002800"}, // Enter
{"LogicCode": 114, "DriverValue": "0x02000001"}, // LCtrl
{"LogicCode": 115, "DriverValue": "0x02000020"}, // RShift
{"LogicCode": 116, "DriverValue": "0x02002C00"}, // Space
```
then it becomes impossible to remap the special keys independently (for example, if I write "Space:A", it will remap *both* space keys.)

If I, instead, use completely phony DriverValues in keys.json:
```
{"LogicCode": 112, "DriverValue": "0xFF000070"},
{"LogicCode": 113, "DriverValue": "0xFF000071"},
{"LogicCode": 114, "DriverValue": "0xFF000072"},
{"LogicCode": 115, "DriverValue": "0xFF000073"},
{"LogicCode": 116, "DriverValue": "0xFF000074"},
```
and also add corresponding definitions to DriverValue in KeyValues.cs:
```
MBackspace = 0xFF000070,
MEnter = 0xFF000071,
MCtrl = 0xFF000072,
MShift = 0xFF000073,
RSpace = 0xFF000074,
```
then the right space key shows up in "dumpkeys" as RSpace, and I can remap it independently.

But this seems like a nasty workaround.  In particular, it seems like the mapping from physical keys (LogicCode = 116) to labels (RSpace) should probably be defined by model-specific configuration.  I notice that unlike model 656801808, models 656801829 and 656801832 use LogicCode 109 for "Left Space" and LogicCode 110 for "Right Space".

**Comment by pixeltris** [comment]
That workaround does seem like the best way to do it without some structural changes in code. Internally I essentially use a Dictionary<DriverValue, DriverValue> to map keys. For things like LAlt/RAlt there's a unique DriverValue. They don't define a unique DriverValue for MEnter, MCtrl, MShift, etc which means duplicate keys will get mapped to the same thing.

LogicCode is per-model and the value in keys.json isn't used for anything. In model 656801808 profile.json for Enter/MEnter both DriverValue entries are defined as 0x02002800 (Enter). 'Index' (LogicCode) doesn't actually map to anything meaningful outside of the context of that model. e.g. for your keyboard we only know '46' is Enter and '113' is MEnter, but '46' and '113' are specific only to that keyboard and programmatically we don't have any way of knowing that key actually represents Enter/MEnter without looking at its DriverValue. And if we do look at the DriverValue both keys are seen as Enter, as opposed to Enter and MEnter.

Defining a new MEnter key in KeyValues.cs with dummy values seems like a reasonable workaround to me as there isn't any way to map LogicCode values such as '46' and '113' to actual keys. The official software UI doesn't have this problem as they assign keys by their visible location rather than by their name.

Happy to take a pull request with the dummy values and the data files. I would probably make the DriverValue somewhat represent the real value of the key e.g. 0xFF002C00 for space where the real space is 0x02002C00 (so that it can still see it's a space key when it calls GetShortDriverValue) and you might need to add extra handlers where there's special handlers for things like MCtrl/LCtrl/RCtrl e.g. in UserDataFile.cs.

I think the reason why your rows look weird in "dumpkeys" is because your keyboard has non-uniform key locations. The "dumpkeys" tries to build rows based on the change of the Y axis position of the keys, I guess the arching of the keys throws that off a bit.

**Comment by pixeltris** [comment]
As mentioned in #17 the data files have been updated and include these files. There's still a possible issue of the duplicate keys, but there are options available now for automatically dealing with them (providing an alternative name for duplicate key names, or using the duplicate key name variant as show in `dumpkeys`).

Note: The official software is much more updated than the x-bows version of the software, so if you're on Windows you may find it more of an enjoyable experience using the latest version of the official GK6X software.

**Comment by bemoody** [comment]
That's great!  Sorry I haven't had time to tinker with this, but I'm
glad to hear it should now be supported by the "official" data files.

Me, I use Linux, so I very much appreciate having a free + open source
+ cross-platform tool for doing these things.  So thank you for
working on it, and I'll let you know if I see any problems with the
new version.
