### ISSUE TITLE
Unable to connect, never get any console output

### ISSUE THREAD

**Issue by nz8** [pixeltris/GK6X#160]
The software seems unable to detect and/or connect to my GK61v2 keyboard. Also, the GKX6Plus software says "Not Support Device" when opened.

**Comment by pixeltris** [comment]
https://reddit.com/r/GK61/comments/m1ooyp/software_for_gk61v2

Sounds like it's using the GK6X brand name, but uses different software. Not much I can do about that. But you can use their software https://hk-gaming.com/pages/download
