### ISSUE TITLE
Web GUI on Linux

### ISSUE THREAD

**Issue by konsumer** [pixeltris/GK6X#161]
I ran the [GUI release](https://github.com/pixeltris/GK6X/releases/download/GK6X-v1.17/GK6X-v1.17-GUI.zip) like this on Pop!OS 20.10:

```
sudo mono GK6X.exe

Connected to device 'SK96S RGB' model:656801880 fw:v1.15
```

It doesn't  seem to open up 6464 port, and it never logs the URL (which I gather it should from the source.) Do I need to do something else?

**Comment by pixeltris** [comment]
The GUI build just bundles the additional data files for the GUI to function. To actually start the GUI web server, run the `gui` command.

**Comment by konsumer** [comment]
ah! Thanks. That totally made it work.

![Screenshot from 2021-07-27 15-32-27](https://user-images.githubusercontent.com/83857/127236086-7d16b9a6-0194-4d7e-b5ea-0db3c0238960.png)

As a sidenote, great work on this. I was really getting annoyed with having to reboot into widows to configure the keyboard, also their closed-source software totally sketches me out.

I was thinking about porting this to nodejs for cli/lib/electron wrappers, for wider support (and maybe a nicer GUI setup on all OS's). I am not as string with C#, and node has [a great lib](https://github.com/node-hid/node-hid) that works with HID. I will play around with it and see if it's worth the effort, but either way I appreciate all your work that went into this.

**Comment by pixeltris** [comment]
It might be worth checking out the official Mac software which uses electron and node-hid. It also contains additional non-packed js files which might be worth looking at under `\GK6+.app\Contents\Resources\app\`.

**Comment by konsumer** [comment]
Awesome!

**Comment by konsumer** [comment]
Going to close, as my original issue is resolved. I'm also making great progress on [my node version](https://github.com/konsumer/node-gk6x). Thanks for your help, and a great tool!

**Comment by pixeltris** [comment]
Awesome! Added to the related projects in the README.
