### ISSUE TITLE
Trouble opening the web GUI on Mac- file GK6X-v1.17-GUI/open http:/localhost:6464 does not exist

### ISSUE THREAD

**Issue by ya-boi25** [pixeltris/GK6X#163]
This is probably just me being dumb, but still any help would be appreciated. I've followed all the instructions to the best of my knowledge, I downloaded the GK6X-v1.17-GUI zip folder from the releases, downloaded and installed mono, change directory into the GK6X-v1.17-GUI folder and ran `mono GK6X.exe`. As you can see in the console output below, it says I am missing a file. What is this file, and how can I resolve this error? Thank you!

`MacBook-Air:~ Name$ cd /Users/Name/Desktop/GK6X-v1.17-GUI`
`MacBook-Air:GK6X-v1.17-GUI Name$ mono GK6X.exe`
`Connected to device 'GK64XS-RGB' model:656801924 fw:v4.3
gui`
`Started web GUI server at http://localhost:6464`
`The file /Users/Name/Desktop/GK6X-v1.17-GUI/open http:/localhost:6464 does not exist.`

**Comment by pixeltris** [comment]
You should be able to just open the web browser at http:/localhost:6464

That message is a bug where it's attempting to launch a web browser, but the GUI web server should be running. Ref https://github.com/pixeltris/GK6X/issues/128 https://github.com/pixeltris/GK6X/issues/146

**Comment by ya-boi25** [comment]
That works! Thank you!

I have a somewhat unrelated question, so if it would be best to move it to a new issue please just let me know. I seem to have a broken light on my keyboard. The key in the Alt key spot is this shade of yellow-green no matter what I do. Even with all the other lights turned off, this one still lights up. Is this a problem with the hardware itself that would warrant a replacement, or is there something I can do? Thank you!
![150f17ed-82c1-4411-a208-6d864618f431](https://user-images.githubusercontent.com/66101203/127679030-3742b50e-4cb0-4776-844e-5407ae35257b.jpg)

**Comment by ya-boi25** [comment]
Oh wait nevermind, that seems to be some sort of indication that they keyboard is plugged in. This is my first keyboard, so I have a lot of learning to do! Is this an indication of how much charge it has? (It's Bluetooth.) Or does it only say that the keyboard is plugged in?

**Comment by ya-boi25** [comment]
That works! Thank you so much!
