### ISSUE TITLE
Should this work with "SONiX GK630 Gaming Keyboard"?

### ISSUE THREAD

**Issue by konzty** [pixeltris/GK6X#166]
Hi,

I bought this keyboard (SPC GK630K Tournament Kaihl Brown DE) and I was looking for a way to run the Window Software for configuring the keyboard on Linux. Or to find a Linux alternative to the software.
Somehow I ended up here.

I tried using your software but so fwar without success.
sudo mono GK6X.exe runs but no output is generated so I suspect my keyboard is simply not recognized.

The question though is - Should my keyboard even be recognized? I'm not sure if your software is the right thing for my keyboard.

Here is the output from dmesg when I connect the keyboard:
```
[ 2393.057490] usb 5-1: new full-speed USB device number 2 using xhci_hcd
[ 2393.228444] usb 5-1: New USB device found, idVendor=3299, idProduct=4e61, bcdDevice= 1.00
[ 2393.228447] usb 5-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 2393.228449] usb 5-1: Product: GK630 Gaming Keyboard
[ 2393.228450] usb 5-1: Manufacturer: SONiX
[ 2393.241184] input: SONiX GK630 Gaming Keyboard as /devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb5/5-1/5-1:1.0/0003:3299:4E61.0007/input/input30
[ 2393.301289] hid-generic 0003:3299:4E61.0007: input,hidraw2: USB HID v1.11 Keyboard [SONiX GK630 Gaming Keyboard] on usb-0000:0c:00.3-1/input0
[ 2393.306362] input: SONiX GK630 Gaming Keyboard as /devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb5/5-1/5-1:1.1/0003:3299:4E61.0008/input/input31
[ 2393.365225] input: SONiX GK630 Gaming Keyboard System Control as /devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb5/5-1/5-1:1.1/0003:3299:4E61.0008/input/input32
[ 2393.365297] input: SONiX GK630 Gaming Keyboard Consumer Control as /devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb5/5-1/5-1:1.1/0003:3299:4E61.0008/input/input33
[ 2393.365394] input: SONiX GK630 Gaming Keyboard as /devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb5/5-1/5-1:1.1/0003:3299:4E61.0008/input/input34
[ 2393.365447] input: SONiX GK630 Gaming Keyboard Mouse as /devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb5/5-1/5-1:1.1/0003:3299:4E61.0008/input/input35
[ 2393.365536] hid-generic 0003:3299:4E61.0008: input,hiddev1,hidraw3: USB HID v1.11 Keyboard [SONiX GK630 Gaming Keyboard] on usb-0000:0c:00.3-1/input1
```

And thats the lsusb entry:
`Bus 001 Device 008: ID 3299:4e61 SONiX GK630 Gaming Keyboard`

Should it work? Could you make it work? Can I help you test it?

cheers,

konzty

**Comment by pixeltris** [comment]
Unfortunately not. They are using a 'GK' prefix in their product names, but are unrelated. The vendor/product id don't match up to the ones belonging to the GK6X brand.

But maybe their software works under [Wine](https://www.winehq.org/), or a VM.

**Comment by konzty** [comment]
Thank you very much for taking the time to answer this!

So far I was not successful with Wine, the software starts flawlessly but unfortunately it doesn't discover the keyboard either. I'll try my luck with a VM next.

Merci!
