### ISSUE TITLE
Need help with remapping keys to Arrows keys (GK61X)

### ISSUE THREAD

**Issue by rgvxsthi** [pixeltris/GK6X#167]
Hi guys, trying to use the AUR package with the "/map" parameter for my text file. I'm trying to remap the keys as follows:

1. Slash:Up
2. RAlt:Left
3. RCtrl:Right
4. Menu:Down
 
My config file is as follows:

```
[Base]
Slash:Up
RAlt:Left
RCtrl:Right
Menu:Down
```

Code output is as follows:
```
sudo gk6x /map '/home/rgvx/Desktop/123.txt'
Filename: /home/rgvx/Desktop/123.txt
Connected to device 'GK61X RGB' model:656801837 fw:v1.16
Done
Disconnected from device 'GK61X RGB'
```

But the keys are still not remapped. Please guide me in the right direction with what mistakes am I making?

**Comment by pixeltris** [comment]
The custom file name needs improvements really. Currently a custom file must be in the `UserData` directory (no full file paths), and the code auto appends the `.txt` part.

https://github.com/pixeltris/GK6X/blob/96e9c041778c9370f9bf06000d687f4873fbb468/GK6X/Program.cs#L669

So for your case if you wanted to use `123.txt` you'd need to put it into the `UserData` directory, and do `/map 123`.

**Comment by rgvxsthi** [comment]
Thanks for your reply @pixeltris !

Tried with the edits and the new folder for the file but still failed:

```
❯ sudo gk6x /map 123
[sudo] password for rgvx: 
Filename: 123
Connected to device 'GK61X RGB' model:656801837 fw:v1.16
Done
Disconnected from device 'GK61X RGB'
```

**Comment by pixeltris** [comment]
Maybe there's a bug with the `/map` command line arg. Maybe try editing the generated file which should be `UserData/656801837.txt` then starting gk6x with no command line args, then type `map`.

**Comment by Jonavin** [comment]
When you use /map it assigns the name of the parameter and sets the command queue to “map”. It should be the same as typing “map” itself after it is loaded. 

I haven’t tested if the behaviour is different in Linux.  Does the mapping work when running normally using the standard filename in the user data location?

**Comment by rgvxsthi** [comment]
Okay so @pixeltris 's recommendation worked for me when using the latest release package (and using the extracted UserData folder) rather than AUR package. Thanks!
