### ISSUE TITLE
No devices connector error

### ISSUE THREAD

**Issue by a-harigovind** [pixeltris/GK6X#168]
Hi 

I'm using the [HK Gaming GK61 ](https://www.amazon.in/HK-Gaming-Mechanical-Illuminated-Programmable/dp/B07TH7SN8M/ref=sr_1_1) and I tried compiling this code. But I get the error stating "No devices connected" even though the keyboard is connected and working. 

Any ideas what the issue might be? Thanks in advance for any help!

**Comment by pixeltris** [comment]
This keyboard isn't compatible and has its own dedicated software as mentioned here https://github.com/pixeltris/GK6X/issues/160
