### ISSUE TITLE
Need help with not existent key

### ISSUE THREAD

**Issue by keteflips** [pixeltris/GK6X#170]
Hi all.

I have a GK61 and I dont have the <> ( lessthan greaterthan) keys in my keyboard. I want to map this keys to a layer but in the  "dumpkeys" I dont have the keys.

How I can make this to work?

Thanks all for your job.

**Comment by pixeltris** [comment]
I think you'll need to use a macro for that as `<>` are only accessible via the shift modifier on `,.`

```
[Macro(LessThan)]
Up:LShift
Press:Comma
Up:LShift

[Macro(GreaterThan)]
Up:LShift
Press:Period
Up:LShift

[FnLayer3]
Q:Macro(LessThan)
W:Macro(GreaterThan)
```

That example should map `<>` using macros to `Q/W` on layer 3.

For a full list of keys see https://github.com/pixeltris/GK6X/blob/96e9c041778c9370f9bf06000d687f4873fbb468/GK6X/KeyValues.cs#L269

**Comment by pixeltris** [comment]
Even if you don't have the key on the keyboard that mapping should still work. An example of mapping Q to F13 on layer 3 is as follows:

```
[Layer3]
Q:F13
```

If you have comma/period, but LShift doesn't produce </>, then what does it produce?

**Comment by keteflips** [comment]
Wroks perfect!!!!!

#Mayor que menor que
Comma:AltBackslash
Period:Macro(Great)

#Macros
#>
[Macro(Great,10,RepeatXTimes,1)]
Down:LShift
Press:AltBackslash
