### ISSUE TITLE
MK61 Software Issue

### ISSUE THREAD

**Issue by lildmon** [pixeltris/GK6X#173]
How can I change my backlight, while still having the ripple effect in the MK61 software, or on the MK61 itself? To sum it up, how can I somehow put a Base color (let's say purple), and my Reactive color (let's say Ripple, whit the color red)? Because my friend has the Apex Pro and he is able to do that. Or is it just not possible whit the Gamakey MK61?

**Comment by pixeltris** [comment]
The MK61 isn't actually a GK6X keyboard and uses different software / protocols, so I'm unable to help with that. Ref https://github.com/pixeltris/GK6X/issues/117
