### ISSUE TITLE
Cannot restore capslock

### ISSUE THREAD

**Issue by deli-gajigesa** [pixeltris/GK6X#174]
Hi,

Currently on I'm having problem that after I remap my **CapsLock** into **Esc** on **layer 1**, I cannot restore it back to CapsLock (both remap it back or use unmap), even my base layer & layer 2 also becoming Esc.

However remapping to other alphanumeric keys works fine.

Tried remap with official software not working, using restore function from official software also not working.

Here some info system I use
- Macbook Pro M1 16GB
- OS: `MacOS Big Sur 11.5.1`
- Mono: `Mono JIT compiler version 6.12.0.122 (2020-02/c621c35ffa0 Wed Feb 10 00:51:43 EST 2021)`
- Keyboard: `GK-64XRGB`
- Keyboard firmware: `v1.16`
- Official Software version: `v1.0.6`

**Comment by pixeltris** [comment]
That's odd. Hard to tell what's going wrong there. `unmap` uses the default config which could potentially be wrong, which may also be impacting `map`.

I assume it fixes itself when you use your dedicated reset key combo?

What is the model id? I'll have a look to see if there's anything weird going on in the data files.

**Comment by deli-gajigesa** [comment]
This is what I've got when using mapper
`'GK64X-RGB' model:656801836 fw:v1.16`

**Comment by deli-gajigesa** [comment]
Hi,

I found the culprit, after checking system preferences, I found out that I previously map my Capslock to Esc and forgot about that, after I did restore default the Capslock working again.

Sorry for the hassle, I will close the issue. Thanks
