### ISSUE TITLE
Support for Kemove Shadow?

### ISSUE THREAD

**Issue by mdietrich16** [pixeltris/GK6X#175]
I have a Kemove Shadow DK61 which does not seem to work with this software. When I start the program with sudo there is nothing displayed, not even a failed handshake message. Since there was a changelog note 'Add "Kemove Driver" files' and the Kemove Snowfox mentioned in #76 is basically the same keyboard I thought it might work. Is this expected or can it be made to work? If so. I would be very happy to provide all the details needed.

**Comment by juliojgd** [comment]
@mdietrich16 I can't see in #76 any confirmation of Kemove Snowfox working at all. I own a Kemove Snowfox and it did not work. Why you presume that Snowfoxis working with this software?

**Comment by pixeltris** [comment]
I think if it's a compatible GK6X keyboard which is missing data files the following should be outputted to the console, if it isn't a compatible keyboard it wont output anything

https://github.com/pixeltris/GK6X/blob/96e9c041778c9370f9bf06000d687f4873fbb468/GK6X/KeyboardDeviceManager.cs#L226

Based on their website it should be `DIERYA DK61 Pro` and `DIERYA DK66` which are supported. `DIERYA DK61E` uses different software.

**Comment by mdietrich16** [comment]
@juliojgd I just assumed that the owner closing the issue after mentioning a fix was an indication of it working, even if not stated explicitly. I must have assumed incorrectly, sorry.

**Comment by mdietrich16** [comment]
@pixeltris Oh, ok. Since I get no output when running `sudo gk6x` when connecting my keyboard via bluetooth or cable, it must be a `DIERYA DK61E` or something else. Shall I close this then? And do you have any other idea what software I could use on linux?

**Comment by pixeltris** [comment]
You should be able to identify the device/vendor id through the Linux command `lsusb` (or similar). GK6X boards are `1ea7:0907`.

There is software for `DIERYA DK61E` [on their site](https://kmovetech.com/art/https-kmovetechcom-software-download.html), so if it's that make you could try running it under Wine (or a Windows VM if Wine doesn't work). The alternative is to reverse engineer their software and implement it in a similar way to this project.
