### ISSUE TITLE
GK68xs remapping issue Z:Y

### ISSUE THREAD

**Issue by assignUser** [pixeltris/GK6X#176]
I have an issue with flashing the following mapping:
```
[Base,Layer2]
Subtract:Slash
Slash:Subtract
Z﻿:Y
Y:Z﻿

[Base,Layer1,Layer2,Layer3]
Menu:RCtrl
Space_4:AltBackslash
```
This exact config works fine on my gk61x but on my gk68xs the switching of z and y fails for some reason and the original y key becomes completely unresponsive and does not trigger any keycode (confirmed with findkeys, no reaction at all not even null). The switching of Slash and Subtract work without an issue though...

I have tried flashing this with the newest commit compiled with mono on pop_os 21.04 and with 1.17 on windows, both with the same result. 

Any idea what the issue could be or how to better troubleshoot it?

**Comment by pixeltris** [comment]
If you have a mapping with nothing other than `Y:Z` does that work? Same for `Z:Y`.

Based on the key bring unresponsive under `findkeys` it sounds like the key isn't set up correctly in the data files so it's incorrectly mapping it. What is the modelid?

**Comment by assignUser** [comment]
I tried to map some different config (just Y:Z/Z:Y, both etc.) as you requested. While doing that it worked as expected, then stopped again and then worked again, at the moment I can not reproduce the bug reliably for what ever reason, sorry :/ 

For completeness sake my model is: 656801834 fw:v1.19
I will close this issue and reopen it in case I can reproduce the issue.

p.s. thanks for this software! It really adds a lot of value to the gk6x boards!

**Comment by pixeltris** [comment]
Weird, sounds like a bug in mapping. I'll play around at some point and see if I can reproduce.

**Comment by assignUser** [comment]
I have not had the tiem for more tests but it might not be happening anymore because I stopped mapping this to the base layer. I Will update when I had time to test.

**Comment by assignUser** [comment]
I think we could proceed with the release? Or do you have some other things you want to implement before release?
