### ISSUE TITLE
Can't remap arrow keys in base layer

### ISSUE THREAD

**Issue by carlosGG97** [pixeltris/GK6X#177]
I've tried many ways of doing it after reading the documentation and I just can't seem to get it right, What I want to do is map the arrow keys to FN+WASD. This is my map file:

[Base]
CapsLock:LCtrl
LCtrl:CapsLock

[FnLayer]
A:ArrowUp
A:ArrowLeft
S:ArrowDown
D:ArrowRight

the base layer portion works simply fine
[656801884.txt](https://github.com/pixeltris/GK6X/files/7508877/656801884.txt)

**Comment by pixeltris** [comment]
As mentioned in the readme `The base layer fn key set can't be mapped.` and as such `FnLayer` isn't a valid. Only `FnLayer1`, `FnLayer2`, `FnLayer3` are supported.

Unfortunately it's a limitation of the firmware.

**Comment by f7urry** [comment]
so, its because the firmware, we cant remap Fn+Backspace = Del?

**Comment by pixeltris** [comment]
On the base layer, yes this is a firmware limitation. On other layers you can map Fn+Backspace=Del
