### ISSUE TITLE
Question: fix broken firmware

### ISSUE THREAD

**Issue by dulceVillabona** [pixeltris/GK6X#180]
Hi, sorry to bother you, I was wondering if this would help me fix a GK61 that stopped working after updating the firmware from the official site. None of the keys work and only a few light up, I havent found a way to fix it yet. Thanks in advance.

**Comment by pixeltris** [comment]
That might be hard to fix. You could try the key combo which resets your keyboard to default settings, but it probably wont help in this case.

Maybe reach out to the people you got the firmware from? There are quite a few variants of the GK61 board so it might not be correct, getting the original firmware might be tricky as well (I'm not aware of any official way to do so).
