### ISSUE TITLE
GK61: Fn key and Lighting not working

### ISSUE THREAD

**Issue by ksalanga** [pixeltris/GK6X#183]
**OS:** Ubuntu 20.04.3 LTS

**GK Board:** 'GK61X RGB' model:656801837 fw:v1.19

**GK6X Version:** GK6X-v1.18

**Install:** (Source) .tar.gz

**Config:**

_656801837.txt_

`[Lighting(Windmill,Base)]`

**Setup:**

I installed mono, built the GK6X.sln with msbuild, and went into /Build and ran sudo mono GK6X.exe.

**Problems:** 

- Base Firmware Fn and any FnLayer mapping does not work
- Keyboard does not light up after Installation and Setup

**Solutions I've Tried:**

- For the Fn: I tried adding [FnLayer1,2,3] bindings in the GK61, but none of them triggered when I hold Fn
- For the Lighting: As you can see in the GK61 txt, I added the Lighting mapping, but still doesn't light up

**Note:**
- Mapping seems to work fine on the base layer. I can map any key to any other key
- When I use findkeys command when running the program, every key outputs something **except** for Fn. Is the fn key supposed to not print anything?

Thanks

**Comment by pixeltris** [comment]
`FnBase` doesn't exist as the firmware doesn't support it. `FnLayer1` / `FnLayer2` / `FnLayer3` should work so I'm not sure what is going wrong there. I'm fairly sure I tested those on the latest version. But I'll try again when I next get the chance. Could you perhaps show your mapping?

For the lighting did you enter the "user lighting" mode using your keyboard shortcut? I believe all GK6X keyboards by default start in the "reactive lighting" mode.

The `findkeys` command can't remap `Fn` so it doesn't display anything when pressed.

**Comment by ksalanga** [comment]
My mapping is on the config in the post. It's just that one line:
`[Lighting(Windmill,Base)]`

Also, I'm not sure what you mean by the user lighting mode in the keyboard shortcut.
Here's the GK61 manual:

- https://preview.redd.it/wcx0z1r7wro41.jpg?auto=webp&s=360a392f905db678730a614fe85c54773599ec7b
- https://ae01.alicdn.com/kf/H0b908fc29ec74efbaccba8c68885984cZ.jpg

Can't seem to find anything that's meant by User Lighting or Reactive Lighting mode.

Also, Fn commands just don't work in general when I start the software. 
For example, if I hold FN + W, I expect nothing to appear because in the standard firmware, FN + W switches me to FnLayer1, but on my Ubuntu system with this GK6X driver installed, FN + W just types w or W if I'm holding shift.

Do you know if anyone else has had issues with the Fn not working with your program and if they found a fix?

**Comment by pixeltris** [comment]
The terminology varies on keyboards. But in your case it should be:

- `FN + ]}` - Reactive lighting (called mode 1-5 in your manual)
- `FN + \` - User lighting (called mode 6-9 in your manual)

By default it uses the first lighting mode (which can't be reconfigured). So try `FN + \` a few times to see if your user lighting shows up. I just tested this with `Windmill` and it worked fine for me on v1.18.

---

I meant your mappings for the `FnLayer1` / `FnLayer2` / `FnLayer3` which you haven't been able to get working.

Let me demonstrate some mappings for you on my GK68. It uses the same layer switching keys as yours - FN+W (layer 1), FN+E (layer 2), FN+R (layer 3).

```
[FnLayer1,FnLayer2,FnLayer3]
V:C
```

With the above mapping V outputs C as expected on FN layer 1-3. When shift is held down it is capitalized. When I'm not in layer 1-3 or not holding down the FN key V is outputted as expected.

```
[FnLayer1]
W:C
```

With the above mapping it behaves in the same way as the V:C example. In this case I'm only mapping on FN layer 1. As I press FN+W to get into layer 1 I'm now unable to leave layer 1 by pressing FN+W (as it's overridden and outputs C). Though I can press FN+R twice to get back to the base layer.

---

I'm confused this:

> Fn commands just don't work in general when I start the software

Running this software has no impact on the keyboards operation by itself. It maps the keys when you use the `map` command which sends all of the key info data to the keyboard and it's saved onto the flash memory of the keyboard (i.e. the keyboard doesn't depend on GK6X running).

Pressing FN+W with the software running and then doing so again without the software running should produce identical results.

The only exception to this is the `findkeys` command which is a diagnostics tool and doesn't provide any functionality other than for diagnostics. But again, this only runs if you run the command (and stops once you close the software, or leave the FN+Q layer).

---

> Do you know if anyone else has had issues with the Fn not working with your program and if they found a fix?

I believe you're the first person to have issues with the FN layers not working with this software. Other than this (which is yours) https://github.com/pixeltris/GK6X/issues/103
