### ISSUE TITLE
my mk61 is not recognized by the software

### ISSUE THREAD

**Issue by ITzBielKB** [pixeltris/GK6X#184]
I installed the mk61 software in several ways, through the official Gamakey website and through several video links, including recent videos, but none of these attempts were successful, in the software it appears only on the device (no device), in addition to Windows recognizing it as SK61L, I wanted to know if there's a solution, I'll wait carefully.

**Comment by pixeltris** [comment]
English only please. I've used google translate to convert the title / description to English.

MK61 is not a GK6X supported keyboard. See https://github.com/pixeltris/GK6X/issues/117#issuecomment-853684254

**Comment by ITzBielKB** [comment]
I have installed the mk61 software in various ways, through the official Gamakey website and through several video links, including recent videos, but no attempt has sucessful, in software it appears only no device, and the Windows recognizes it as SK61L, I wanted to know if there is a solution,
Note: The installed software is called MK Series.
thaks for atention :)

**Comment by ITzBielKB** [comment]
I have installed the mk61 software in various ways, through the official Gamakey website and through several video links, including recent videos, but no attempt has sucessful, in software it appears only no device, and the Windows recognizes it as SK61L, I wanted to know if there is a solution,
Note: The installed software is called MK Series.
thaks for atention :)

**Comment by ITzBielKB** [comment]
I have installed the mk61 software in various ways, through the official Gamakey website and through several video links, including recent videos, but no attempt has sucessful, in software it appears only no device, and the Windows recognizes it as SK61L, I wanted to know if there is a solution,
Note: The installed software is called MK Series.
thaks for atention :)

**Comment by pixeltris** [comment]
As mentioned in linked issue MK61 isn't supported by the software in this repo. A [banggood](https://www.banggood.com/Gamakay-MK61-Wired-Mechanical-Keyboard-Gateron-Optical-Switch-Pudding-Keycaps-RGB-61-Keys-Hot-Swappable-Gaming-Keyboard-p-1797608.html) listing links to [this](https://drive.google.com/file/d/1Puj6QBxviU98ZO2jmZCFtyoEJr1BJvT_/view?usp=sharing) and [this](https://drive.google.com/file/d/1drczjZ0ifAJIffam4W9NM_Esf7EEEf5n/view?usp=sharing). Also read [this thread on reddit](https://reddit.com/r/MechanicalKeyboards/comments/lnz63m/software_for_the_gamakay_mk61).

That's about as much as I can help with as I'm not familiar with the software or the protocols it uses. Hopefully you can get something to work following those links.

**Comment by ITzBielKB** [comment]
thanks bro :)
