### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by SosPosos** [pixeltris/GK6X#185]
for some reason mapper doesn't map all the time.. and i want to ask how i choose what lighting effect to use? 

and another question.. does lighting effect which works when you press on key exist with single color, and not this rainbow mess.. btw, software is really cool, thank you!

**Comment by SosPosos** [comment]
And what base layer is? it's not the driver layer, yes? Can i change driver layer (not fn functions)?

**Comment by pixeltris** [comment]
The mapper can silently fail. And if there are syntax errors it currently doesn't warn you about them https://github.com/pixeltris/GK6X/issues/138

The base layer is the default layer (i.e. when you hold down your FN key it wont highlight the active layer as it's in the base layer). Layer1-3 will highlight the given layer key when the FN key is held down.

The driver layer isn't implemented as it requires constant communication with the software which wasn't something I was interested in. To use the driver layer try out the official software which does support it.

There are some samples of lighting in the sample txt file https://github.com/pixeltris/GK6X/blob/master/Build/UserData/Sample.txt

Newer keyboards only support mapping lighting to the base layer (it carries over to all the other layers). So the first lighting example in that file is worth trying out.

There isn't any support for complex lighting effects such as when you press individual keys. However, there are in-built lighting effects which do that. Check our user manual on how to change between the two lighting effect modes.

**Comment by SosPosos** [comment]
It worked after i reset keyboard and then map from official firmware 🤷‍♂️
Steange. Btw, do you plan to make key combos like "alt+d = del" possible? Is it possible at all?

**Comment by pixeltris** [comment]
Unfortunately it isn't possible to map key combos like that. You can do something like:

```
[Base]
Delete:LAlt+D
```

But the protocol doesn't support doing it the other way around.

**Comment by SosPosos** [comment]
That's so sad.. It almost the best keyboard in the world.. Oh.. Anyway, thank you!
