### ISSUE TITLE
support for the hk gaming gk61 v2 (gk61us) please!!

### ISSUE THREAD

**Issue by yazoo11** [pixeltris/GK6X#187]
the hk gaming software is awful i cant do anything with it

**Comment by DudeDamage** [comment]
Same issue here the app won't detect the keyboard. It would awesome if this got fixed

**Comment by bloemer** [comment]
+1 here.
Or at least a guide to add this keybaord to the drivers

**Comment by pixeltris** [comment]
Unfortunately GK61US is a different type of keyboard which happens to share the same brand name, but is otherwise incompatible at a protocol level.

This project doesn't aim to support keyboards which use the GK brand name but not the protocol used by the GK keyboards.
