### ISSUE TITLE
Assign LE files per keypress on the base layer

### ISSUE THREAD

**Issue by avollrath** [pixeltris/GK6X#188]
Hi there,

great work! In the official software it's possible to assign LE files to keypress events. I'd like to light up the same led for all keypresses on the base layer so that I can use it to trigger a solenoid. Is it possible to add this functionality?

BR

André

**Comment by pixeltris** [comment]
I didn't implement that unfortunately as if I recall the functionality of key press lighting is quite limited. The in-built ones are far superior.

https://github.com/pixeltris/GK6X/blob/6ef1a8012beeb5fdd891906a6569bd0fc3209d75/GK6X/OpCodes.cs#L57-L60
https://github.com/pixeltris/GK6X/blob/6ef1a8012beeb5fdd891906a6569bd0fc3209d75/GK6X/CommandLogger.cs#L192-L200

**Comment by pixeltris** [comment]
Closing as I don't have any plans to implement this due to the limitations of it.
