### ISSUE TITLE
Unable to download release - "virus" found

### ISSUE THREAD

**Issue by Milanzor** [pixeltris/GK6X#19]
Hi there Pixeltris,

I'm trying to give your software a go, I want to bind my keys to combinations of F24 + the key so I can remap my second keyboard using AutoHotKey, however if I download the released version, my Chrome, Edge and Windows native "anti-virus" are showing signs of virusses in the zip file. I'm assuming they are false positives. But is there something you can do about this?

Thanks!

**Comment by pixeltris** [comment]
No idea why antivirus is complaining. You can always build the project yourself if you are concerned. You can compile it with Visual Studio, or the command line compiler (msbuild.exe) which is distributed when installing the .NET runtime.
