### ISSUE TITLE
How do I use the GKPlus driver to update?

### ISSUE THREAD

**Issue by NovaViper** [pixeltris/GK6X#190]
Hi! I downloaded the GK6X Plus driver, as per the [Updates.txt](https://github.com/pixeltris/GK6X/blob/master/Build/Data/Updating.txt) file but now I'm confused on how to I navigate the rest of the steps. How do I use the exe file I get from the official website and navigate to "GK6XPlus Driver/CMSEngine/driver/"?

Also, the Tronsmart link displays a "page not found" error when I go to it, and the jikedingzhi is all in a different language, making it hard to read and the file you get from the page is an exe file.

**Comment by pixeltris** [comment]
I keep meaning to update those instructions... I have updated to the latest data files (V6.0.0.54) but haven't had the chance to test yet. I will push / make a release when I have the time.

**Comment by NovaViper** [comment]
Ah ok! I was wondering because I saw that the driver had an update on the website. Thanks for the info ^^

**Comment by pixeltris** [comment]
I've pushed that out. I'll try to update those instructions at some point...
