### ISSUE TITLE
Not creating txt file

### ISSUE THREAD

**Issue by dierentuin** [pixeltris/GK6X#2]
When I open the program it's just black with a blinking cursor. The txt file UserData/YOUR_MODEL_ID.txt doesn't get generated.

**Comment by pixeltris** [comment]
It should print to the console when it finds and connects to the keyboard, at which point it should create the text file. Are you on Windows? Does the official software work for you? If it does then you could try debugging this to ensure it's connecting to the keyboard https://github.com/pixeltris/GK6X/blob/a2360793140fab4f961ab4ac071462364f6a1cef/GK6X/KeyboardDeviceManager.cs#L81

**Comment by tayumpee** [comment]
I was able to solve this issue by unplugging and plugging the keyboard back in after the program was running.
