### ISSUE TITLE
Unable to make multiple Macros

### ISSUE THREAD

**Issue by Milanzor** [pixeltris/GK6X#20]
Hi there,

My current map file is this:

```
[Layer3]
Left:Macro(Left)
Right:Macro(Right)


[Macro(Left,0,RepeatXTimes,1)]
Down:F24
Down:Left
Up:Left
Up:F24

[Macro(Right,0,RepeatXTimes,1)]
Down:F24
Down:Right
Up:Right
Up:F24
```

However, only the top Macro ever works, if I switch them, the other seems to work. 
I tried looking at the source to find the correct way to make multile Macros but failed to see how it's done, could you point me in the right direction?

Awesome project by the way, it allows me to do exactly what I want with my keyboard where the official software lacks that!

p.s. I compiled from source

**Comment by pixeltris** [comment]
Are you using the binary build from the releases page? I haven't updated that in a while. There was a fix for macros here https://github.com/pixeltris/GK6X/issues/9

**Comment by pixeltris** [comment]
If you compiled from source it should work. There was a issue with multiple macros before but it should be fixed https://github.com/pixeltris/GK6X/issues/9

**Comment by Milanzor** [comment]
I'll give it a go with the A key.

If it doesn't work, would you be willing to help me get it fixed? I'll buy you a coffee!

**Comment by Milanzor** [comment]
Seems to be the same with the A key.

This is me UserData file:

```
[Layer3]
Left:Macro(Left)
Right:Macro(Right)

[Macro(Right,0,RepeatXTimes)]
Down:A
Down:Right
Up:Right
Up:A
[Macro(Left,0,RepeatXTimes)]
Down:A
Down:Left
Up:Left
Up:A
```


Is this how your test looked?

**Comment by pixeltris** [comment]
Yea, that works for me using the latest code.

**Comment by Milanzor** [comment]
Really? That literally does not work for me. I've got the following device: ```Connected to device 'GK64S RGB???' model:656801802 fw:v1.5```

**Comment by pixeltris** [comment]
Can you confirm that this line of code exists in your GK6X/KeyboardDevice.cs file at line 296?

https://github.com/pixeltris/GK6X/blob/3a7c3c2b025197961596799c4d458d615e557d4c/GK6X/KeyboardDevice.cs#L296

**Comment by Milanzor** [comment]
I'm the worlds biggest idiot! It does work. I was deeply under the impression I was on the latest version, while I wasn't.


Very sorry for the inconvenience!

**Comment by pixeltris** [comment]
No worries, good that it's working.
