### ISSUE TITLE
Temporary switch layer button + Modifiers

### ISSUE THREAD

**Issue by devinoct** [pixeltris/GK6X#21]
Hello, pixeltris.
Thank you for your time and effort that makes this keyboard more usable in other OSes.

Because we can't move the FN key(or copy the functionality to other key), the temporary switch layer workaround works great, except it has drawback.
You need to press the TempSwitchLayer FIRST before any modifier, for example if you want to type tilde/grave you need to press this in order **TempSwitchLayer + Shift + Esc**, won't work if you press **Shift + TempSwitchLayer + Esc**.

Any workaround for this? This is the only inconvenient left for me and i'm sure a lot of people want to move the FN key, at least for me it has to be on CapsLock especially on 60% keyboard.

I'm using GK61.

**Comment by pixeltris** [comment]
Unfortunately there aren't any workarounds for this as far as I'm aware. To do this you would need to make changes to the firmware.

**Comment by devinoct** [comment]
That is very unfortunate indeed, well time to get used to it then.
Thanks!
