### ISSUE TITLE
What is 'driver' mode?

### ISSUE THREAD

**Issue by raelmax** [pixeltris/GK6X#22]
Hi, I'm trying to use your project(thank you!) but I'm not familiar with some concepts. What means 'driver' mode that you talk in README?

**Comment by pixeltris** [comment]
There are 3 main layers which get stored on the keyboard itself. There's a 4th layer which the manufacturer calls the 'driver' layer which essentially only operates when there is constant communication with the keyboard.

This constant communication allows for finer control of what happens such as when a macro key is pressed (it's possible to do all kinds of fancy dynamic lighting effects, open software, execute code, etc).

**Comment by raelmax** [comment]
Thanks for your explanation! That's clear now. Thank you! :)
