### ISSUE TITLE
Macro examples

### ISSUE THREAD

**Issue by f4k3-pixel** [pixeltris/GK6X#23]
First of all, thanks for this awesome project!

If possible can you share more macro examples?
Also, can others share their respective config files?

Some more macro examples will be helpful, as I didn't quite get how to create some types of macros

**Comment by pixeltris** [comment]
My config file is extremely simple, I only map the 'Pause' key on my GK84 to 'Delete'.

Is there a specific macro you would like an example of? Here's a couple of macros other people have used:

https://github.com/pixeltris/GK6X/issues/20#issue-611357661
https://github.com/pixeltris/GK6X/issues/9#issue-540425243

**Comment by f4k3-pixel** [comment]
For example, a macro for pressing Ctrl+x and then Ctrl+s
A few more examples would be beneficial as I found out that I can do
Backslash:LAlt+Tab
a lot later than I should. If such an example was included in the docs, it'd have been helpful :D

**Comment by pixeltris** [comment]
This will map the Q key to do Ctrl+X, Ctrl+S with no delay between the two presses.

```
[Macro(QuickCutSave)]
Press:LCtrl+X
Press:LCtrl+S

[FnLayer3]
Q:Macro(QuickCutSave)
```

You could do something like `[Macro(QuickCutSave, 1000)]` if you wanted a 1 second delay between the Ctrl+X and the Ctrl+S.... though just trying that now all delays seem to register at half the duration.

I will add the `Backslash:LAlt+Tab` thing to the samples.

**Comment by f4k3-pixel** [comment]
Thanks for the example! I understood my mistake :D
I need a slight delay (C-x C-s is save in Emacs :sweat_smile:
