### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by staffiere** [pixeltris/GK6X#25]
How do i compile this?

**Comment by pixeltris** [comment]
There are pre-built binaries on the releases page if you don't want to compile it yourself https://github.com/pixeltris/GK6X/releases

If you want to compile it, you can use visual studio or MSBuild.exe which should be available on most Windows machines at "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe" pass the GK6X.sln file in as a command like argument, and it will compile it.

**Comment by staffiere** [comment]
nothing happens when i launch the EXE a blank command window just opens and nothing happens.

**Comment by pixeltris** [comment]
Try unplugging and re-plugging your keyboard. It will write to the console window when it connects to the keyboard.

**Comment by staffiere** [comment]
okay, but nothing happens still. it says its connected but nothing else has changed the command window just sits idle.

**Comment by pixeltris** [comment]
Once it's connected you can find your model file under `UserData/YOUR_MODEL_ID.txt` which you can use to configure your keys. After you have done so, you can use the 'map' command. This is stated on the main page https://github.com/pixeltris/GK6X
