### ISSUE TITLE
Assigning a Fn-Layer a different lighting scheme

### ISSUE THREAD

**Issue by f4k3-pixel** [pixeltris/GK6X#27]
By default, before using the GK6X project, my keyboard's FnLayer1 had a cool separate color scheme i.e. On pressing Fn on Layer1, the lighting setup would change, to highlight the F1-F12 keys rather than the arrow keys on the default Layer1.

Is this possible to configure using GK6X?

I had tried something like [Lighting(Turquoise Light,FnLayer1)]
but it doesn't work.

**Comment by pixeltris** [comment]
Are you able to show me how to reproduce that with the official software? Currently the code doesn't support that.

**Comment by f4k3-pixel** [comment]
I don't know about how to do it in the official software but it was the way the keyboard initially was. That configuration was lost once I used GK6X.

**Comment by f4k3-pixel** [comment]
What's key-press lighting? Are you talking about the reactive lighting feature?

**Comment by pixeltris** [comment]
If you use the reset keyboard state key combo it should re-add the lighting effect if it comes with your firmware. Yea key-press lighting is reactive lighting.

**Comment by f4k3-pixel** [comment]
What's the key combo for that? I saw some reset combos on the internet but they didn't work for my board :(

**Comment by pixeltris** [comment]
Mine is fn+q+esc. All boards should have a reset. Try finding the manual for your board online (or request one from your keyboard manufacturer).

**Comment by f4k3-pixel** [comment]
It flashes the keyboard's "boot animation" on mine and seemingly erases only the base layer's lighting which is brought back by hitting any of the lighting keys. So essentially it does nothing and the firmware is not reset

**Comment by pixeltris** [comment]
Yea that should be it. It sounds strange that the lighting isn't reset, but unfortunately it does sound like that F-key lighting is gone. You could try contacting jikedingzhi (software / firmware developers) if it's important to you. Currently I have no knowledge of how it could be done from what I've observed so far from the official software.

**Comment by f4k3-pixel** [comment]
Okay. I have no idea of how to contact them but it's not a deal-breaker, so it is fine.
