### ISSUE TITLE
Shift layer as different keys?

### ISSUE THREAD

**Issue by f4k3-pixel** [pixeltris/GK6X#28]
Is it possible to, for example, map something else like '+' to Shift+4, instead of '$'?
Or is that something that is only possible on QMK boards?

I wanted to only "configure" the Programmer Dvorak's numbers section on one layer for practice.

**Comment by pixeltris** [comment]
This is the only way I can think of doing that. It changes LShift to switch to layer1, then in layer 1 it maps '4' to '+' (though that will mean '4' will always result in '+' when on layer1, regardless if shift is held down).

```
[Base]
LShift:TempSwitchLayer1

[Layer1]
D4:LShift+Add
```

**Comment by f4k3-pixel** [comment]
Well, I do have 4 layers.... maybe I can lose one as a compromise.
Thanks for the example. I'll try it out.

Is it possible to use some other key for TempSwitchLayer1 and use shift as the normal thing? As in with temp switch layer (let's say which is mapped to \) , pressing \ 4 will give $ and pressing \ shift 4 will give +? 

Or, is it possible to have 3 things bound to a single key with different modifiers to access them.

**Comment by pixeltris** [comment]
Each key can only be mapped to a single value. For example you can't have 'A' map to 'G'+'H'. But for regular keys you can apply modifiers such as LCtrl, RAlt, etc so that you can map 'A' to 'LCtrl'+'G'.

TempSwitchLayer1-3 are their own unique values and can't be combined with things such a modifiers. You can obviously map any key to TempSwitchLayer1-3 (doesn't have to be LShift).

I can't really help much beyond that knowledge so I'd just suggest playing around knowing the limitation of the key mappings and see if you can get it doing what you want.

**Comment by f4k3-pixel** [comment]
I thought that it should be possible as ESC definitely does work this way.

**Comment by pixeltris** [comment]
Again, I'd just suggest getting familiar with how the logic of key mappings work to try and do what you want. The TempSwitchLayer1-3 values can let you do interesting things as you're obviously switched to another layer when those keys are held down.

**Comment by f4k3-pixel** [comment]
ESC is ESC
Fn+ESC is `
Fn+Shift+ESC is ~

But okay, I'll play around and see what I can do.
Thanks!

**Comment by pixeltris** [comment]
Yea the backtick key (`) and the the tilde key (~) are the same key. In this project that key is called "BackTick". When you hold down LShift you get the tilde. The mapping for that would be as follows:

```
[Base]
Escape

[FnBase]
BackTick
```

As you can see there's nothing special going on with escape, there are just two different rules (one for regular keys and one for fn keys)

**Comment by f4k3-pixel** [comment]
Hmmm....yes. But it'd have been useful to have →
4                → 4
Shift+4       → $
Fn+4          → F4
Fn+Shift+4 →Something else?

Side question → If not on the GK boards, is this possible on QMK?

**Comment by pixeltris** [comment]
Pretty much anything is possible on QMK (as it's fully programmable / open source). The GK6X firmware only allows for basic mapping. What you're wanting to do isn't possible with what's available with configuring GK6X boards.
