### ISSUE TITLE
Set one-shot and hold behaviors to keys

### ISSUE THREAD

**Issue by raelmax** [pixeltris/GK6X#29]
Hi, I've configured the FnLayer1 with my remaps, but I want to enable this layer temporarily when holding some key. I've tried to use Backspace, but since I've remapped this key to ESC, I'm not able two keep these two behaviors(one-shot ESC, holdingTempLayer1) on the same key. There some way to configure this?

**Comment by pixeltris** [comment]
There isn't any way to do this as each key is mapped to a single value. Regular keys can be combined with modifiers (LShift, RCtrl, etc), but the temp layer keys are their own unique values which can't be combined with anything.
