### ISSUE TITLE
GK64 issue

### ISSUE THREAD

**Issue by jfklivez** [pixeltris/GK6X#30]
Hello, pixeltris! First, I apologize for writing this here and it is completely unrelated to the tool you built, but I am definitely not the best person to find another way to contact you and I am desperate. I recently got this keyboard (https://imgur.com/a/pE3kdDK) as a gift. Personally, my knowledge is close to none when it comes to custom stuff and complex software, but I am having an issue with this one and I love it so much and I can't just let this go - I have tried so hard to fix this. Both the ESC and Delete keys are not working. This is what the keys look like in the windows software (https://prnt.sc/sfpop9), it looks like they are not recognized or disabled maybe. I have tried clicking "restore" thinking it's going to rever it to factory settings, still nothing. I have also tried the follwing: reinstalling the software, use a different type-c:usb cable, replace the switch with a spare switch, change between layers, remove the switch, remove both switches, replace the switch with one from an already working key. I also took it to a repair service which has 3 people with huge experience in fine electronics, they checked the soldering and the contacts and after several tests, they told me that the contacts and the soldering is perfect and does not need to be fixed. They claim that the issue could only be programmatic or a software error. 

If you have any sort of idea what could cause this issue I would be forever grateful because this is my first keyboard of this kind and I don't really have the funds to buy a new one right now. Thank you so much!

**Comment by pixeltris** [comment]
https://github.com/pixeltris/GK6X/commit/b6105c40c37cc1004cbb0c64a877ed39fe06ab73 in this commit I added a command called 'findkeys'. It will map ALL keys on your keyboard to a callback and will display the index / key info for that key when pressed. If your esc/del keys are available to map they should appear there.

There's a binary with this on the releases page if you want to try this out without compiling anything https://github.com/pixeltris/GK6X/releases

Heed the warning when using the command as you will most likely need to restart your machine after using it (it will stick down invisible ctrl/shift/alt keys).

**Comment by jfklivez** [comment]
Hello pixeltris! You're doing God's work my man, I'll hand it to you! Even though I am with a really limited knowledge when it comes to fine software tools like this one, I had no issues installing it and using the "findkeys" command.  You can see what I got here: https://prnt.sc/shjjph .

I pressed ESC + Del a thousand times, it seems like it's not working. I have been working on trying to flash the firmware and the only tool I could find was a QMK Toolbox. I can't connect my keyboard there and I genuinely have no idea what am I doing.

**Comment by pixeltris** [comment]
So it sounds like it's either a firmware issue or possibly still maybe a hardware issue. This site is the only distributor that I've heard mention firmware updates http://www.pc-100.com/ and they target iGK64 I think (not sure if that's actually different to the regular GK64 or not). Their downloads are behind a login page so I'm not sure about the direct links but you can sign up and look at posts such as http://www.pc-100.com/custom-mechanical-keyboard-community/software-firmware-manuals-tools/rescue-tool-for-firmware-updating-failed-for-igk6x-keyboard-igk61-igk61p-igk62-igk64/

I would probably suggest seeing if you can get a replacement from where you got it from, as it does sound like there's some issues with your board.

**Comment by Meepoker** [comment]
Hi, I recently received my GK64XS (Bluetooth version RGB), i tried your software and I had issues with the FN key after a reset on the official software. The keyboard is currently set in "driver" layer.

1) I tried dump keys functionality and found, the FN key has numerical values instead. Is this normal?

Fn = 4294967295

2) In "Findkeys" functionality, tapping on the FN key does not pickup anything in the terminal.

Is the FN key dead?

**Comment by pixeltris** [comment]
The FN key is a special key which isn't mappable and therefore wont broadcast itself when pressed using the 'findkeys' command. 4294967295 (aka 0xFFFFFFFF) states a key isn't mapped to anything and should use its default value. As FN isn't mappable anyway assigning a value to FN will be ignored by the firmware.

On the base layer the FN key set isn't mappable (you can't map FN+A for example on the base layer, but you can on other layers). If you're able to get to the base layer and the default FN key mappings don't work on that layer, then yes your FN key is probably dead.

**Comment by Meepoker** [comment]
@pixeltris Noted on that. I tried on the standard layer of the software and tried mapping it. 

the FN key still will not be picked up via the "Findkeys" option. 

I followed up with the Manufacturer, they mentioned it needs a factory reset. However I found no such functionality within the GK6X software driver.

@pixeltris will you add in a "factory reset" functionality for your program?

**Comment by pixeltris** [comment]
The 'findkeys' command is just to identify key indices / locations. It doesn't map the FN key set as it doesn't provide any more index / location information over the regular key set.

There's a factory reset key combination on all GK6X boards. On mine it's FN+Q+Esc held down for 5-10 seconds. Check with the manual for your device to find what your key combination is.

There isn't any way to access the factory reset functionality from software.
