### ISSUE TITLE
Failed to download v1.6 with Chrome - Virus detected

### ISSUE THREAD

**Issue by KarBoy2314PL** [pixeltris/GK6X#31]
i uuh idk even how can an open source program be classified as a virus xd

anyone has ideas on what to do? I know that it's "not a virus" and all of that jazz

**Comment by pixeltris** [comment]
I'm not sure why stuff keeps detecting it as a virus, there isn't anything conspicuous about it other than interacting with HID devices for talking with the keyboard.

The only thing I can suggest is downloading it with a different browser (or ignore the chrome warning if that's possible).

**Comment by KarBoy2314PL** [comment]
tried Edge - file contained a virus and was deleted, gonna try Firefox in a bit

**Comment by KarBoy2314PL** [comment]
managed to download it with Firefox, I guess third time's a charm

**Comment by pixeltris** [comment]
Frustrating that it happens, but not much that can be done really. Glad you finally managed to download it though.
