### ISSUE TITLE
Compiling error?

### ISSUE THREAD

**Issue by RenatoAfonsoTD** [pixeltris/GK6X#32]
I'm getting this when trying to compile...

Program.cs(316,47): error CS0246: The type or namespace name 'KeyboardDevice' could not be found (are you missing a using directive or an assembly reference?)
Program.cs(321,47): error CS0246: The type or namespace name 'KeyboardDevice' could not be found (are you missing a using directive or an assembly reference?)
Program.cs(335,73): error CS0246: The type or namespace name 'KeyboardLayer' could not be found (are you missing a using directive or an assembly reference?)

(csc on macos)

**Comment by pixeltris** [comment]
csc as in the C# compiler? Have you tried MSBuild?

**Comment by RenatoAfonsoTD** [comment]
Ah! I knew I was forgetting something. Worked :)
