### ISSUE TITLE
Operation did not complete successfully because the file contains a virus or a potentially unwanted software

### ISSUE THREAD

**Issue by KarBoy2314PL** [pixeltris/GK6X#33]
continuing my 'venture from #31, now I can't open the software, giving me this error
![explorer_2020-05-15_18-26_2EFFRku461](https://user-images.githubusercontent.com/8020330/82073723-ec9cf380-96d9-11ea-9562-83dd10467558.png)

i... uhh... have no idea anymore

**Comment by pixeltris** [comment]
If you're having issues you could build the code yourself and copy that 'driver' folder from the GK6X-v1.6 folder.

If you want to compile it without having to install visual studio there are two ways to do it. Using MSBuild.exe or csc.exe which should be located at `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\`

If MSBuild is in that folder that's the best thing to use as it's simple and resolves everything for you.

`C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe C:\GK6X\GK6X.sln`

If only csc is there then you can use the following (it will output an exe called Program.exe and you'll want to copy that to the Build folder along with HidSharp.dll).

`>C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe /unsafe -recurse:"C:\GK64\GK6X\*.cs" /r:"C:\GK64\GK6X\HIDSharp\HidSharp.dll"`

**Comment by pixeltris** [comment]
Thinking about it it's probably this code that is making it throw a hissy fit https://github.com/pixeltris/GK6X/blob/master/GK6X/CommandLogger.cs I'll look at disabling it for future builds as it isn't used.

**Comment by KarBoy2314PL** [comment]
I do have MSBuild, so i made a bat to execute MSBuild pointing at GK6X.sln and ran it as admin, it successfully compiled and i successfully ran the exe!

geez finally- BUUUUT typing "gui" and pressing Enter gives me "Couldn't find data path; Started web GUI server at http://localhost:6464" <-- this might need to go to a separate issue maybe

yea, try taking a look at the CommandLogger thing, maybe something will fruit out of this

**Comment by pixeltris** [comment]
You need to make sure you have the 'driver' folder (from the GK6X-v1.6.zip) in the location where the .exe is.

**Comment by KarBoy2314PL** [comment]
i uhh... don't think i have that folder anywhere from the build directory...?

![O7r1nw6yVC](https://user-images.githubusercontent.com/8020330/82078605-b2375480-96e1-11ea-9d3d-f9ce236c3400.png)

**Comment by pixeltris** [comment]
You need to copy it from the GK6X-v1.6.zip. That folder doesn't exist in the source code in this repo (as it contains a lot of bloat / images that aren't needed normally). You need it get it from the zip.

**Comment by KarBoy2314PL** [comment]
OOH, okay, got it, and localhost works now!

thanks for help, you might wanna make a guide if this issue occurs to anyone else (or maybe just reference to this and my previous issue)

you can close now

**Comment by pixeltris** [comment]
Hopefully it should fix itself when the CommandLogger code is disabled. There is a note on the README about the additional files (mentioning you can get them from the official software, or use the pre-built version).
