### ISSUE TITLE
having trouble configuring GK64 RGB V1 with Web GUI

### ISSUE THREAD

**Issue by KarBoy2314PL** [pixeltris/GK6X#34]
ok, so my keyboard reports as "GK64 RGB V1" (model ID is 656801802) and I do everything through the localhost GUI thing

after playing around with the GUI thing I uuh noticed a couple of issues:
1. I can't change light effects for layers 1 2 3 
2. I can't modify the layers' key inputs
3. there's a standard layer AND a Fn+Q layer, which is default and has no light effects (further investigation shows that there's a offline standard layer AND an online layer... uuh... okay?)
4. the GUI doesn't save anything to UserData/656801802.txt
5. Attempting to Apply while on a Layer freezes the button, the keyboard's light effects don't disappear for a second and nothing happens, replugging the keyboard shows the default config again

What I CAN do is:
1. set light effects to standard layer BUT ONLY to Logic Lights (that's what they are called in the manual, it's Fn+CloseSquareBrace if you're wondering), there's nothing I can see regarding Code lights (Fn+Backslash) <-- I successfully changed Full Green Light to HustleandFlow, Save and Applied with success too)
2. I can make a macros folder and make, record and save a macro, but i can't put it on keyboard (problem 2)
3. Make a light effect file and apply it to Code lights list

my guess is something is wrong regarding indexing of the layers, cuz i noticed there are multiple versions of the GK64 and maybe the configs were copy-pasted throughout the duplicates without further investigation

couple misc questions:
1. will it help if i provide the serial ID of my keyboard?
2. do you plan on modifying and/or rewriting the gui software? kinda referencing to #15 

also sorry for bothering you with so many issues, I just want to put all of the software problems to end

**Comment by pixeltris** [comment]
As mentioned I've barely tested it so yea issues are to be expected.

The Web GUI uses its own separate storage of configuration, so it isn't compatible with the commands like 'map' / 'unmap'. It saves things into /driver/UserData/.

The lighting effects on layers 1,2,3 are configured differently to the lighting effect on the base layer. On the base layer you put your lighting into those 5 slots. On layers 1/2/3 you select the lighting effect you want on the list on the right hand side, then click save, then click apply.

'offline' (aka 'driver' layer) isn't supported by my code.

If the 'Apply' button freezes that means something is broken (and nothing will actually apply). Open the developer console (F12 on most browsers) and look at the console log to see what errors there are.

I'm not sure what you mean exactly by 'Logic Lights' / 'Code lights'. GK6X have 3 different forms of lighting:

- Regular lighting effects which constantly play (we can configure these).
- Reactive lighting effects which do things like highlight which keys you pressed, lights up rows of lights relative to the key you pressed, light up keys when the keyboard mic hears noise, etc. These are hardcoded on the firmware and cannot be modified.
- Key-press lighting effects. These play a lighting effect one time when you press a key. These can be configured per-key. I didn't implement this as it generally looks awful.

If the 'Apply' button successfully executes it should elevate not being able to map keys. It sounds like something isn't currently handled properly so the 'Apply' button hangs and things cannot map. See the browser console log for the errors.

**Comment by KarBoy2314PL** [comment]
in the [GK64 manual](https://static-resources.imageservice.cloud/2257738/gk64-mechanical-keyboard-kbdfans.jpg) that's what they are called. So I guess Fn+CloseSquareBrace is Regular lighting and Fn+Backslash is Reactive lighting

and here's the console after changing the light effect on a layer
![chrome_2020-05-16_10-40_8fLXWgATi6](https://user-images.githubusercontent.com/8020330/82115212-bc993300-9761-11ea-9b04-cc62c5e4384e.png)

**Comment by pixeltris** [comment]
Sounds like an exception is being thrown in https://github.com/pixeltris/GK6X/blob/b81e32980f5c224b9a47b924fe40665433503d06/GK6X/WebGUI.cs#L441

You'd need to log the error here to get more information https://github.com/pixeltris/GK6X/blob/b81e32980f5c224b9a47b924fe40665433503d06/GK6X/WebGUI.cs#L866

**Comment by KarBoy2314PL** [comment]
where could I find that in the chrome dev console? btw your program doesn't log anything regarding gui

**Comment by pixeltris** [comment]
What I linked is on the C# code (the server part). It sounds like it's hitting that "catch" line of code. So you need to change that to do something like this:

```
catch(Exception e)
{
    Program.Log("Exception: + e.ToString());
}
```

Then you can check the console to see what it logs, and then diagnose the issue from there.

**Comment by KarBoy2314PL** [comment]
so what you're telling me is:
- fork the code, edit WebGUI.cs
- inside that file, replace lines 866-869 with what you gave me
- download the source, compile it with the MSBuild thing
- find the error from there

...right?

**Comment by pixeltris** [comment]
I missed a quotation mark

```
catch(Exception e)
{
    Program.Log("Exception: " + e.ToString());
}
```

**Comment by KarBoy2314PL** [comment]
yup, that fixed it, here's what i got

![GK6X_2020-05-16_15-32_DFtVuRNUm4](https://user-images.githubusercontent.com/8020330/82121027-70161d80-978a-11ea-93c9-0657a3e65186.png)

**Comment by pixeltris** [comment]
I guess you can just delete that line of code as I was just using that for some temporary logging stuff.

**Comment by KarBoy2314PL** [comment]
Do I remove lines 512-516 or just line 514?

**Comment by pixeltris** [comment]
Just 514

**Comment by KarBoy2314PL** [comment]
that fixed it, it also fixed other problems regarding GUI configuration!

so for testing purposes I did this

![chrome_2020-05-16_16-19_fOYq9evGEf](https://user-images.githubusercontent.com/8020330/82121955-fd5c7080-9790-11ea-8493-c08499f38f7d.png)

hit apply, it succeeded, and reprogrammed ZXCV worked! hooray!

**Comment by pixeltris** [comment]
Nice.

**Comment by KarBoy2314PL** [comment]
closeable? maybe apply all of the things you mentioned in your code?

**Comment by pixeltris** [comment]
Sure will do. I'll put an updated release and hopefully the exe wont get flagged anymore as well.

**Comment by pixeltris** [comment]
I guess it would be nice to look into what causes the "standard" (base) layer from not being editable in the web GUI (seeing as you can edit it using the commands and stuff). I think the limitations on that are in 0.js but I haven't spent much time trying to fix it up.
