### ISSUE TITLE
Can't set a lighting profile to Driver layer

### ISSUE THREAD

**Issue by KarBoy2314PL** [pixeltris/GK6X#35]
I put this in UserData/"keyboard id here".txt

```
[Lighting(Star lighting,Base)]
[Lighting(Flame,Driver)]
[Lighting(Full Red light,Layer1)]
[Lighting(Full Green light,Layer2)]
[Lighting(Full Blue light,Layer3)]

[FnLayer1,FnLayer2,FnLayer3]
Q:DriverLayerButton
W:Layer1Button
E:Layer2Button
R:Layer3Button
```

then

used "map" in console
once done, I see Star lighting
did Fn+Q and I don't see the Flame pattern, I see blank
did Fn+W and I see Full Red light
same goes for Fn+E and Fn+R

I have a bad feeling you can't change any keys in the Driver layer, either.
also is the FnDriver layer a thing?

**Comment by pixeltris** [comment]
The 'driver' layer (also known as the 'online' layer) isn't supported as mentioned in #1 

It requires constant communication with the keyboard and eats CPU cycles constantly sending the realtime lighting data to the keyboard every frame, and when you disconnect your board you can no longer use that layer until you reconnect it to that same machine running the same software setup.

I might look at supporting it one day as you can do interesting things with macros as each time you press a macro on that layer it actually sends the key to the software (so you can do stuff like launch programs, etc).

**Comment by pixeltris** [comment]
Closing in favor of #1
