### ISSUE TITLE
Lighting effect types and Specific color gradient

### ISSUE THREAD

**Issue by f4k3-pixel** [pixeltris/GK6X#36]
I figured that the "Type" field in the lighting files is static when 0 and the entire rainbow spectrum when 1. Is there a way to set a custom gradient to it? For example, cycling through all the shades of blue? Is there a way to specify new "Types" and are there any more types available?  

And what exactly does "Count" do?

**Comment by pixeltris** [comment]
I'm honestly not too sure on lighting effects. How they're set up is a bit convoluted. I think to do a gradient you just need to add a bunch of frames with different colors? Maybe look at some of the existing lighting effects and see if they kinda do something similar and try modifying them.

**Comment by f4k3-pixel** [comment]
What do frames do? I actually didn't understand how to use them/what they are.
I've already modified many lighting effects to my lighting :D 

Count does control the speed but I don't know the exact units/ what else it can do.

**Comment by pixeltris** [comment]
Honestly I'm not very familiar with the format of it anymore. They are files from the official software. The GUI is a little better for creating lighting effects.

There's some code here related to the lighting effects with some notes:

https://github.com/pixeltris/GK6X/blob/edcc42e01839db53818f62054e1b2d0a853c9a89/GK6X/UserDataFile.cs#L234

There's two related notes
`"Count" (used in RGB / breathing)`
`"StayCount" (used in breathing)`

**Comment by f4k3-pixel** [comment]
Ok, thanks for the help.

But what are frames?

**Comment by pixeltris** [comment]
"Magic Waves" is an example of something that uses frames. Different rows of keys are lit up each frame until the "wave" reaches the bottom of the keyboard, at which point it repeats. It combines it with the dynamic RGB lighting.

![image](https://user-images.githubusercontent.com/6952411/82122803-a012f000-978d-11ea-93c2-5a59fd275d10.png)

**Comment by f4k3-pixel** [comment]
So frames are essentially different isolated regions for combining different things in a single config?

**Comment by pixeltris** [comment]
I think they are useful if you want the appearance of something "moving". Stuff like Windmill gets away without having to use frames because they use the dynamic RGB stuff. But I think where that reaches is limits in cases such as highlighting different keys over time.

For example if you wanted to make like a "snake" lighting effect where say 4 keys are lit up and they move around the keyboard like the game "snake". That could only be achieved using frames.

**Comment by f4k3-pixel** [comment]
Okay, I understood what they are for. Thanks! I'll play around and experiment :D

**Comment by pixeltris** [comment]
This is an example of what I mentioned. This is using different layers for the 'snake' like effect and using RGB for fancy RGB lighting. It's definitely easier using the GUI to edit lighting effects. I need to add some command to export lighting effect files from the web gui to the regular folder....

![image](https://user-images.githubusercontent.com/6952411/82123947-14e92880-9794-11ea-8cb3-4c81539d62e8.png)

**Comment by pixeltris** [comment]
You can now copy lighting effects from the web gui by running the gui and then typing `gui_le YOUR_EFFECT_NAME` e.g. `gui_le snake`. It will copy the effect over to the main /Data/ folder which allows you to use it via the map command.
