### ISSUE TITLE
Doesn't work on Linux, get System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by veronikazaglotova** [pixeltris/GK6X#41]
- OS: **Arch Linux**
- Kernel version: **5.6.11**
- Versions afffected: **All**

Current newest version, compiled with msbuild version 16.5.0-ci, shows [this](https://0bin.net/paste/xdIDsG6MaOL-8sb+#c19lcQq-cyDhcMtjtX+uD+Deg/sn9Kapcs+S8+xlcId)
GK6X version 1.8, downloaded binary from "Releases" page shows [this](https://0bin.net/paste/nLRcO3NBKf63SM3P#XXGygGzFmI9DpJV0V097AZ3mznwgVF0PsNJiJXRPOXD)
I tried the version 1.0 which I tried several months ago and it seemed to work (I didn't really use it because I was lazy and didn't understand why nothing is happening because I didn't RTFM) and it shows [this](https://0bin.net/paste/CPoXlNYB0U6ViAl+#HxzFXQb89khi+i+uonAQ9K-jMazWiz7q3GRomaD+qYY)
I don't see any reason to show other logs because they are the same and only differ in the same place at `[0x00...] in <abgg86590...>:0`, tell me if you need them.
So I guess the problem is not with the project itself, but something with my OS? What is wrong here? Am I missing some packages? Or something happened to Mono?

**Comment by pixeltris** [comment]
It looks like it isn't too happy with one of the connected devices on your machine.

Maybe try putting a try/catch over this block of code:

https://github.com/pixeltris/GK6X/blob/cdcd03707bd2265dedb15b715697cf8bd1ad2d4a/GK6X/KeyboardDeviceManager.cs#L89

**Comment by veronikazaglotova** [comment]
Hello. I tried disconnecting my XP-Pen graphics tablet that I use instead of my mouse, it works now.
I don't know how to code, unfortunately, how do I put a try/catch?

**Comment by pixeltris** [comment]
https://github.com/pixeltris/GK6X/commit/0f9ee54559ffb468211083ccbccbe5d3658f9d4a this commit should fix it. I'll put out an updated release at some point.

**Comment by veronikazaglotova** [comment]
Sikved

**Comment by veronikazaglotova** [comment]
Issue is solved. Thank you pixeltris, very cool
