### ISSUE TITLE
Macro not working

### ISSUE THREAD

**Issue by sheenp333** [pixeltris/GK6X#42]
Hi pixeltris, thanks a lot for a great project.  I'm trying to set up an alternate Fn Key functionality by using non-function keys in Layer1.  So I use LCtrl to go to Layer1 and map all the non-function keys which have a function in Base layer to that same function.  That worked.  I then had the idea of writing a macro to press the key and return to the base layer by pressing the Layer1Button.  I also wanted to remap quotes key to LWin. The key press works but the return to base layer doesn't.  This is my config:
[Base]
 LCtrl:Layer1Button
[Macro(QuotesBase)]
Press:Quotes:100
Press:Layer1Button
[Base]
Quotes:LWin
[Layer1]
Quotes:Macro(QuotesBase)
[Layer1]
 W:Layer1Button

I've tried various combinations of Layer1Button and W key but not sure why it doesn't work.  Can you suggest something else?

Thanks
Pat

**Comment by pixeltris** [comment]
Unfortunately macros are only capable of pressing basic keys. Stuff that begins with 0x02 in this list:

https://github.com/pixeltris/GK6X/blob/0f9ee54559ffb468211083ccbccbe5d3658f9d4a/GK6X/KeyValues.cs#L269
