### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by aheil** [pixeltris/GK6X#45]
The code is currently not licensed in any way.

It would be useful if you would provide a license.

**Comment by pixeltris** [comment]
I could add MIT or something, though keep in mind this project uses js/json files taken from the official software.

**Comment by pixeltris** [comment]
https://github.com/pixeltris/GK6X/commit/07f8e564393d1ed0910abd068cd0764a42a5c4f2 sets the license to MIT, with a disclaimer stating that files under `/Build/Data/` are not covered by this license as they belong to `jikedingzhi`.
