### ISSUE TITLE
Map RAlt to Fn+RAlt on base layer

### ISSUE THREAD

**Issue by prashantbaid** [pixeltris/GK6X#46]
Hi, first of all, thanks for making this. I am using Mac OS X and this has been a life saver.

I am using GK61 and wanted to map RAlt key to Fn+RAlt to use it as the Left Arrow key. 

I tried this - `RAlt:Fn+RAlt` on base layer but it doesn't seem to work.

From the README I can see that Fn is not mappable on base layer, but is it possible the other way round like above?

**Comment by pixeltris** [comment]
Why not just map `RAlt` to `Left`?

It isn't possible to map something like `RAlt` to `Fn+RAlt`, but it is possible to map `Fn+RAlt` to `RAlt` or `Left`. The reason is that `Fn+XXXX` isn't a keycode that a computer understands so you cannot map keys to fn keys.

**Comment by prashantbaid** [comment]
The problem is GK61 does not come with a dedicated `Left` key. 

`Left` works as `Fn+RAlt` on base layer. I was hoping to find a way to map it to just `RAlt`. 

Looks like there is no way to do this.

**Comment by pixeltris** [comment]
You should be able to map `RAlt:Left`. It doesn't matter if the keyboard doesn't have the desired key physically on the keyboard.

**Comment by prashantbaid** [comment]
Wow, this worked!! Thanks for your help :)

Closing the issue now.
