### ISSUE TITLE
Weird GK61? (Unmap and Base Layer not working)

### ISSUE THREAD

**Issue by DigitalJosee** [pixeltris/GK6X#47]
Hey,

I'm trying to learn how to use GK6X, and I don't know if my keyboard is acting weirdly or what, but I can't set any lightning on Base layer (it just doesn't work), Layer1/2/3 works just fine. Also I can't unmap it, if I try to run it, it says done but don't unmap anything.

I'm using pretty simple configs, as show:
```
[Lighting(Star lighting,Base)]
[Lighting(WASD static,Layer1)]
[Lighting(Full White Light,Layer2)]
[Lighting(GK61 Diffusion,Layer3)]
```

My Keyboard is: `Connected to device 'GK61-RGB-V2' model:655491246 fw:v1.32`

Thanks a lot for your awesome tool!

PS: Is it possible to use Fn+W for any mapping? I don't think so, but since it's on your sample.txt, maybe it works and I'm doing something wrong, i.e
```
[FnLayer3]
W:LCtrl+LAlt+Delete
```

**Comment by pixeltris** [comment]
Hmm there's something weird going on. I couldn't map mine either. I then tried resetting my keyboard using the dedicated keyboard reset combo, and tried GK6X-v1.7 and that worked, since then the latest version has also worked for me. I'm not sure if it was the keyboard reset that fixed it or v1.7. I also think I observed layer 1 lighting breaking briefly after that as well. I'll keep my eye out and see if I can reproduce exact steps to create this bug.

Your ctrl+alt+delete thing seems to work for me.

**Comment by pixeltris** [comment]
Try using your keyboard reset combo (mine is fn+q+esc on GK84), then see if the tool maps lighting correctly. I think some state is possibly messed up and can no longer correctly map the lighting?

**Comment by pixeltris** [comment]
Also `unmap` only unmaps keys, it doesn't touch lighting. [NoLighting] in `map` will clear existing lighting. I think it could possibly be [NoLighting] was is messing some things up, not 100% sure. Haven't found the route cause of this yet.

**Comment by DigitalJosee** [comment]
> 
> 
> Try using your keyboard reset combo (mine is fn+q+esc on GK84), then see if the tool maps lighting correctly. I think some state is possibly messed up and can no longer correctly map the lighting?



> 
> 
> Hmm there's something weird going on. I couldn't map mine either. I then tried resetting my keyboard using the dedicated keyboard reset combo, and tried GK6X-v1.7 and that worked, since then the latest version has also worked for me. I'm not sure if it was the keyboard reset that fixed it or v1.7. I also think I observed layer 1 lighting breaking briefly after that as well. I'll keep my eye out and see if I can reproduce exact steps to create this bug.
> 
> Your ctrl+alt+delete thing seems to work for me.

My bad actually, I was pressing Backspace instead of ], now it looks to grab lighting on base just fine.

Also, how can Fn+W work? When I press Fn+W, instead of using my mapping, it just change to Layer1.

**Comment by pixeltris** [comment]
Ohhh, Fn+Q/Fn+W/Fn+E change layers on GK61 don't they? As they are dedicated keys for switching layers they can't be mapped unfortunately. You could use a different key other than one of those though.

**Comment by DigitalJosee** [comment]
> 
> 
> Ohhh, Fn+Q/Fn+W/Fn+E change layers on GK61 don't they? As they are dedicated keys for switching layers they can't be mapped unfortunately. You could use a different key other than one of those though.
> 
> Check your keyboard manual for the system mapped fn keys.
> 
> Looks like this thread mentions some of them https://old.reddit.com/r/MechanicalKeyboards/comments/furxbt/gk6164_software_basics_guide/

Yeah, I was like, "Hum, I don't think that's possible", anyway, thanks for this great app!
