### ISSUE TITLE
It is can off led when press fn? (not issues)

### ISSUE THREAD

**Issue by 1ocate** [pixeltris/GK6X#48]
Thank you so much made this project.

After I use this almost problem gone and become comfortable.

The last things I want when press fn, dont want led on.. not led effect.

Always fn press on layer status led turn on (examle if my layer 1 when press fn will led on 'W' led)

I know this is not relation this project but just finding..

Thank you so much..

**Comment by pixeltris** [comment]
I'm not sure if that can be configured or if that's built into the firmware for your keyboard. Maybe you could state your keyboard name in case someone knows a workaround to get rid of that lighting when fn is pressed?

**Comment by 1ocate** [comment]
@pixeltris Thank you for reply. hummm .. that part hard..

So now I try other key map to fn key

but it is not works... sorry can you help me?

<img width="212" alt="image" src="https://user-images.githubusercontent.com/29521447/85917874-225ffb00-b888-11ea-8e13-488930564748.png">

when I try "dumpkeys" Fn = 4294967295

And try 4294967295 in layer 1 = deleate  like this

<img width="249" alt="image" src="https://user-images.githubusercontent.com/29521447/85917928-8682bf00-b888-11ea-8357-1fbf46dc0fc9.png">

But it's not working.. why?

Thank you so much

**Comment by pixeltris** [comment]
What you attempted to do there is make the 'Delete' key press the 'fn' key. This isn't possible as computers don't have a concept of 'fn' keys, only keyboards do. You can only map keys to other real keys.

4294967295 also essentially means 'undefined' / default value of the key as defined by the firmware. It essentially means the key is unmappable.

**Comment by 1ocate** [comment]
Thank you explain.. now give up..
But already woking good coz your great project.
Thank you.
