### ISSUE TITLE
I don't know where to tell about this issue, pls halp

### ISSUE THREAD

**Issue by veronikazaglotova** [pixeltris/GK6X#49]
In the linux terminal, My keyboard seems to do some pretty weird stuff. https://www.youtube.com/watch?v=KYT5qESwEQQ this is my GK61 on default settings, when I type Fn+RAlt it presses the left arrow, but in tty it will make my cursor crazy and able to move freely. Also, I cannot type anything when this bug happens. This does not happen with my rubber dome keyboard
Probably something related to NKRO? Is it possible to try using this keyboard with 6KRO? In GNU/Linux, NKRO doesn't work anyway.
Device: 'SK61 RGB' model:655491117 fw:v1.18
I can bring any information you might need. I am not sure why it says SK61, it's a GK61

**Comment by pixeltris** [comment]
The only thing I can suggest is to try using a program which displays the pressed keys. This might give an indication of what's going wrong.

This project has a command which can display keys when pressed which might give some indication. Use the `findkeys` command. I would also recommending using a third party tool / website to get another view of what keys are pressed.

**Comment by veronikazaglotova** [comment]
I just tried pressing Fn+Alt/Menu/Ctrl/question and [it doesn't even detect Fn and arrow keys](https://www.youtube.com/watch?v=2kKw4fNr2LE)

**Comment by pixeltris** [comment]
So that `findkeys` is used to detect individual keys, so pressing fn keys wont actually show up (as when entering the "driver" mode in this case we don't map any fn keys). The fn key itself wont show up either as it cannot be mapped.

After confirming non-fn keys are behaving correctly with the `findkeys` command I'd recommend using another third party tool or website which displays which keys are being pressed such in the case of your `Fn+RAlt=Left Arrow` case, and ensure nothing more than `Left Arrow` is being detected.

**Comment by veronikazaglotova** [comment]
No keys are being pressed. In fact, I think the tty login screen should be designed to not have such things, because if you do the same with all ttys, then your computer can't work and you have to force reboot your PC. Also, nothing happens when you actually log in and try doing the same with the shell

**Comment by pixeltris** [comment]
I'd recommend using something which displays the exact keycodes pressed. On Windows "Raw Input" would be ideal for this as it gives unfiltered input directly from the keyboard. This could be used to diagnose if the keyboard is registering keys in an unexpected way. I'm not sure what the equivalent of "Raw Input" would be for Linux.

**Comment by skibbipl** [comment]
I believe `showkey` will display keyboard codes in linux.

**Comment by KarBoy2314PL** [comment]
get switch hitter?
