### ISSUE TITLE
Remapping lighting effects keys

### ISSUE THREAD

**Issue by skibbipl** [pixeltris/GK6X#50]
I would like to remap Fn+Backspace (turn on/off lighting) to some other FN combination. But I cannot find key codes for lighting effects in the source code. Is it possible at all?

**Comment by pixeltris** [comment]
Unfortunately the fn key set on the base layer cannot be mapped (firmware limitation). But these can be used to map keys to control the lighting:

```
        NextLightingEffect = 0x09010010,// NOTE: Only works on base layer
        NextReactiveLightingEffect = 0x09010011,// NOTE: Only works on base layer
        BrightnessUp = 0x09020001,
        BrightnessDown = 0x09020002,
        LightingSpeedDecrease = 0x09030002,
        LightingSpeedIncrease = 0x09030001,
        LightingPauseResume = 0x09060001,
        ToggleLighting = 0x09060002,
```

**Comment by skibbipl** [comment]
Yeah, I want to remap keys on Layer1 so I guess this will solve my issues.
