### ISSUE TITLE
Add special key <>|  

### ISSUE THREAD

**Issue by aheil** [pixeltris/GK6X#51]
German keyboard layout provides one special key for <>| (https://en.wikipedia.org/wiki/German_keyboard_layout).
I tried out to find out the corresponding code.  
Is there any way to find out the code to add it to the list of available keys. 

If I can help please let me know how I could contribute.

**Comment by pixeltris** [comment]
What does it say your keyboard name is when it connects to GK6X? I assume it will be a slightly different variant to the regular layouts? The key code should be described under the relevant device here https://github.com/pixeltris/GK6X/tree/master/Build/Data/device

**Comment by aheil** [comment]
When connecting to GK6X I am getting this message: 

Connected to device 'GK64 RGB' model:656801801 fw:v1.5

**Comment by aheil** [comment]
What I am looking for is (based on http://kbdlayout.info/kbdgr/scancodes+virtualkeys) scancode 56 or key OEM_10.

![image](https://user-images.githubusercontent.com/509229/87345159-f31be000-c54f-11ea-904e-0b5cda3ce6e4.png)

I don't find it in the keymaps, however other German special keys like ö,ä,ü work quite well.

**Comment by pixeltris** [comment]
If you use the official software are you able to map it how you want? I'm not seeing anything special in the data files. Unfortunately we are the mercy of how they implemented key mappings. Each key represents a "driver value" which the firmware understands and can convert to key codes to send to the computer.

The values which I have observed can be found here

https://github.com/pixeltris/GK6X/blob/0f9ee54559ffb468211083ccbccbe5d3658f9d4a/GK6X/KeyValues.cs#L269

It sounds like this would key need its own "driver value" which may exist, but I'm not sure what it might be. If it doesn't exist then you're probably out of luck.

**Comment by aheil** [comment]
Thanks a lot for this hint! Using the original Software it worked indeed, using the "backslash" key between left shift and y. It took me ages to figure out how to assign a key.

![image](https://user-images.githubusercontent.com/509229/87356754-ece32f00-c562-11ea-8727-aea114bb7a3d.png)

However, when trying to apply this via  

```
[Base,Layer1,Layer2,Layer3,FnLayer1,FnLayer2,FnLayer3]
CapsLock:Backslash
```

it dit not work. The _KeyValue.cs_ file was the missing link. I found the `AltBackslah `- which was exactely what I was looking for. 

Eventually, the following works perfectly:

```
[Base,Layer1,Layer2,Layer3,FnLayer1,FnLayer2,FnLayer3]
CapsLock:AltBackslash
```

![image](https://user-images.githubusercontent.com/509229/87357116-9e826000-c563-11ea-85e7-924295c7a2b5.png)

Thanks a lot for the hint and the tool in general!

**Comment by pixeltris** [comment]
Ah yea the key naming isn't the best. There's also `dumpkeys` (lists keys as seen in the data files) and `findkeys` (prints keys as they are pressed) commands which are useful for finding key names.
