### ISSUE TITLE
how to run on macos?

### ISSUE THREAD

**Issue by jt3k** [pixeltris/GK6X#53]
macos catalina 10.15.5
i install mono `brew install mono`
then i run the program `mono GK6X.exe`
i see only this text
```
Connected to device 'GK64XS-RGB' model:656801805 fw:v1.15
```

when i disconnect/connect my keyboard,
 in terminal add this lines
```
Disconnected from device 'GK64XS-RGB'
Connected to device 'GK64XS-RGB' model:656801805 fw:v1.15
```

how to run on macos?

**Comment by pixeltris** [comment]
So it sounds like it's running? As mentioned on the readme it's a command line program. Try following these instructions https://github.com/pixeltris/GK6X#usage

**Comment by jt3k** [comment]
hmm, it looks like I have to type commands here

thank you. i try
