### ISSUE TITLE
Remapping RAlt on GK64

### ISSUE THREAD

**Issue by ThatGuyVanquish** [pixeltris/GK6X#55]
First of all - Thanks for this! This has made the experience of using the GK64 so much better than before with the extra possibilities for mapping (I just really don't like the limitation of the official software)

The one thing I can't seem to manage to do is remapping right alt. LAlt works fine, RAlt doesn't seem to do anything.
Is it completely unavailable or am I using the wrong keyname?

Just want to remap it to r/l ctrl (RCTL/LCTL if I found the correct thing on the json file)

Thanks!

**Comment by pixeltris** [comment]
There are two commands which might help out with this `dumpkeys` which prints out the key names as observed in the data files. And `findkeys` which prints out key codes / names as you press keys. You should hopefully be able to use these to identify the key name and map it?

**Comment by ThatGuyVanquish** [comment]
Thanks for the reply
I tried findkeys - seemed to do nothing, which was weird
Then I realized there's a v1.8 and I've been using this since v1.0 or so... facepalm 
My bad, thanks for this - v1.0 had it as 'right ctrl' which basically did nothing, just mapping using v1.8 with the same data files with RAlt: RCtrl fixed my issue
