### ISSUE TITLE
Mapping the Insert Key

### ISSUE THREAD

**Issue by peterzung** [pixeltris/GK6X#56]
Is it possible to map the insert key? I tried ScrollLock:Insert but that didn't work. I also used the command dumpkeys and could not find insert. However, I was able to find the insert button in the GK6XPlus Driver; unfortunately, that software does not allow for remapping in the base layer. There does not seem to be an entry for the Insert key in GK6X-v1.8\Data\device\655491200\data\keymap.js; could that be the problem?

**Comment by pixeltris** [comment]
So dumpkeys shows the keys on your keyboard, but keys can map to any value regardless of whether you have the given key. Perhaps the key you want to map from isn't called ScrollLock? ScrollLock:Insert should work assuming the key you want to map uses that name. You can use the findkeys which will display the name of the key you want to map when you press it.

**Comment by peterzung** [comment]
Thanks for the reply. So it looks like after an update, Microsoft Office turned off the setting "Use the Insert key to control overtype mode," so when I tested to see if the Insert key worked or not, there weren't any responses. However, I also discovered that the value for the Delete key was "undefined" when I used the findkeys command. I was able to correct it by changing
```
{
	"KeyName": "End",
	"Show": "End",
	"LogicCode": 82,
	"LocationCode": 104,
	"Position": {
		"Left": 974,
		"Top": 380,
		"Width": 50,
		"Height": 50
}
```
to
```
{
	"KeyName": "Delete",
	"Show": "Del",
	"LogicCode": 81,
	"LocationCode": 104,
	"Position": {
		"Left": 974,
		"Top": 380,
		"Width": 50,
		"Height": 50
}
```
for v1.8\Data\device\655491200\data\keymap.js

**Comment by pixeltris** [comment]
That's odd. What keyboard do you have? 655491200 is actually the same keyboard I have which is a GK84. My keyboard doesn't have a Delete key on it. I had to map Pause (top right of the keyboard) to simulate the Delete key.

So when you used `findkeys` on that key it displayed something like this?

`Index:81 Name:Undefined Indx:81 Loc:104 D:0x02004C00 S:Undefined`

**Comment by peterzung** [comment]
I also have a GK84 and I was getting the latter
`Index:81 (null)`
This is what my board [looked like](https://imgur.com/vgzlf9m) when I first got it. The delete key is denoted by a garbage can icon and is right above the right arrow key.

**Comment by pixeltris** [comment]
Ah I see, that's interesting! Annoyingly there it doesn't sound like there's a way to differentiate between that variant and the regular layout, so manual modification of the data files does sound like the only real solution in this case.
