### ISSUE TITLE
Base Layer mapping retention

### ISSUE THREAD

**Issue by drummerWill** [pixeltris/GK6X#57]
I am currently on a gk61, and for some reason I have to remap my keys every time I turn my computer on. Here are my mapping commands. 
```
[Lighting(Full Purple Light,Base)]

[Base]
Menu:Down

[Base]
RAlt:Left

[Base]
RCtrl:Right

[Base]
Slash:Up

[Base]
Rshift:Slash

```

**Comment by pixeltris** [comment]
That's odd it should save on the keyboard. Does it reset if you unplug/replug your keyboard? If so I guess there's an issue with the keyboards in-built storage.

**Comment by drummerWill** [comment]
Thanks for the quick response. After making this issue I realized I might have had an issue with something at the end of my config file. This doesn't seem to be an issue with your software, so I'll close this.
