### ISSUE TITLE
TempSwitchLayer is not temporary

### ISSUE THREAD

**Issue by skibbipl** [pixeltris/GK6X#58]
Here is excerpt of my config:
```
[FnLayer1]
RShift:TempSwitchLayer2
LWin:Disabled

[FnLayer2]
LWin:ToggleLockWindowsKey
```
Everything works as expected except the fact that keyboard stays at Layer 2 after pressing Fn+RShift. Is this a limitation of the firmware or this is a bug of the tool?

**Comment by pixeltris** [comment]
That's odd, it seems to work for me. This is what I tried:

```
[FnLayer1]
RShift:TempSwitchLayer2

[FnLayer2]
A:B
```

If I manually switch to Layer1 and then press RShift on that layer it will switch to Layer2 whilst RShift is being held down, and the mapping A:B functions as expected whilst in that temp state.

Maybe try using the official software and see if you're able to do that mapping there?

**Comment by skibbipl** [comment]
The functionality works, but after pressing TempSwitchLayer2 key keyboard switches to the Layer 2 and stays on it. Here is reproduction scenario:
1. Switch to Layer1
2. Press Fn + RShift
Result: Keyboard switches to Layer2 and stays on that layer even after releasing Fn+RShift

**Comment by pixeltris** [comment]
Very odd. Maybe the firmware you're on uses different key values for the temp switch? Again I'd recommend trying to use the official software to see if you get the same issue there.
