### ISSUE TITLE
Support for GK68X & GK68XS

### ISSUE THREAD

**Issue by git2gether** [pixeltris/GK6X#59]
Hi

Please consider adding support for GK68X and GK68XS. There is a large community that is looking forward to some sort of Mac support. 

Thank you

**Comment by pixeltris** [comment]
The data files in this repo are a couple of versions out of date. I'll look at updating the data files soon and hopefully they will include those keyboards.

**Comment by git2gether** [comment]
Thank you, looking forward to it.
