### ISSUE TITLE
How do I run this on macOS?

### ISSUE THREAD

**Issue by AndyrooP** [pixeltris/GK6X#6]
I am completely new to GitHub. How do I run this to remap keys on macOS?

**Comment by AndyrooP** [comment]
I managed to get the model_number.txt file in Build->UserData. But this file is completely blank. How should I edit it to remap keys?

**Comment by pixeltris** [comment]
You could start by trying to map the 'A' key to 'F' for example put in your .txt file the following text, and use the 'map' command in the console. You can also use 'unmap' to reset the keyboard to it's default state.

```
[Base,Layer1,Layer2,Layer3,FnLayer1,FnLayer2,FnLayer3]
A:F
```

Read [Sample.txt](http://github.com/pixeltris/GK6X/blob/master/Build/UserData/Sample.txt) for additional options (lighting / macros) and also see the [list of accepted key values](https://github.com/pixeltris/GK6X/blob/81761765f020962ed04ad68f8f0837facda7a1fa/GK6X/KeyValues.cs#L269) which you can use to map keys.

**Comment by AndyrooP** [comment]
For some reason, I can't seem to access the console in Visual Studio, so I forced the map command by changing the string line to "map".

But when I try the following in the text file:
`[Base,Layer1,Layer2,Layer3,FnLayer1,FnLayer2,FnLayer3]
Ralt:Left

[Base,Layer1,Layer2,Layer3,FnLayer1,FnLayer2,FnLayer3]
Menu:Right

[Base,Layer1,Layer2,Layer3,FnLayer1,FnLayer2,FnLayer3]
RCtrl:Down

[Base,Layer1,Layer2,Layer3,FnLayer1,FnLayer2,FnLayer3]
RShift:Up`
it does not remap the keys as I expect. Is there a way I can remap the keys that I have indicated above to the arrow keys? On the base layer (so I don't have to hit the function button to activate them)? Other key remaps such as A to F in your example work fine.

**Comment by pixeltris** [comment]
That 'Ralt' should be 'RAlt' as it's case sensitive. I tested that exact setup on my keyboard (GK84) and it seems to work for me (although I don't have a 'Menu' key to test).

It could be that your keys are actually mapped slightly differently? Or maybe you have something else in your config that make it fail? You could try typing 'dumpkeys ex' which will dump all of the key names in the order that they appear on your keyboard. It could be that the names are off for some reason.

**Comment by DonaldTsang** [comment]
cross-referencing https://github.com/pixeltris/GK6X/issues/6
