### ISSUE TITLE
[Feature request]Tap&Hold

### ISSUE THREAD

**Issue by veronikazaglotova** [pixeltris/GK6X#60]
I saw a review on the GK66 keyboard, it has a feature that is called "Tap&Hold" in QMK. When you tap a key, it types something, and when you hold it it can switch to a layer or act as a modifier key (not sure about modifiers but the former is totally possible), and it's available for any key.
It's *probably* exclusive to the GK66, but IDK, maybe GK61 also allows for this, or maybe there's a firmware update? I want this feature, this is quite literally what I wanted this whole time: Caps Lock when held is TempLayer, and when tapped it's Escape (very good for Vim and Emacs)
I don't own a GK66 though and I'm not a programmer (yet)

**Comment by veronikazaglotova** [comment]
Forgot to add: this is the video https://youtu.be/CBuz1ZImMsA he starts explaining the feature at around 3:25

**Comment by veronikazaglotova** [comment]
Just downloaded the latest botnet on my Windows PC. Nope, the feature isn't there with my GK61 (labeled SK61 RGB v1.8).

**Comment by veronikazaglotova** [comment]
Downloaded the older botnet that the guy from the video uses. No such feature, either.
The newer botnet I downloaded earlier doesn't allow to change Layer RGB effects, they're only available on the online layer. I wish they weren't such douchebags

**Comment by pixeltris** [comment]
Sounds interesting. Do you know if that feature can be configured on a per-key basis on that keyboard? Or is it exclusive to the space key? I imagine it would be easiest to figure out how it works by having access to that keyboard. It could be a hard-coded feature of that keyboard though, who knows.

**Comment by veronikazaglotova** [comment]
Yes, it can be configured for every key.
I don't have access to that keyboard, I'll look for people who have one on /r/mechtrannicalkeyboards

**Comment by pixeltris** [comment]
So I had a look at this under the UI in developer mode. It looks like the key itself is mapped to a function layer. I tried doing the same on my keyboard and it doesn't behave the same as in the video. I guess that keyboard has special code for it in the firmware? It's hard to tell tbh. Hopefully someone with the keyboard can give some input on this.

**Comment by veronikazaglotova** [comment]
@pixeltris can you tell me how to access the developer mode? I want to try it out on my keyboard UwU

**Comment by veronikazaglotova** [comment]
Onegai desu, how can I access they're developer mode?

**Comment by pixeltris** [comment]
Oh I actually meant developer/debug mode of the software (not the keyboard). What it does is it shows all keyboards in the UI for debugging purposes. Which can be enabled under "Env.json" in the "driver" folder of the official software.

**Comment by willerbee** [comment]
I have the GK61XS (the upgraded version of GK61S and it also has a split spacebar module), it has exactly thesame function as the video, but it only works on the spacebar keys. It's probably reserved for that

**Comment by veronikazaglotova** [comment]
IDK I'm not a programmer and don't know how to find out if it even works on newer boards aaaaaaa

**Comment by pixeltris** [comment]
Yea this feature is reserved for those specific keys. Unfortunately it's a hard coded thing in the firmware and the same logic cannot be used on other keys.

**Comment by MaheshIBM** [comment]
Yes this is something im missing as well, have mostly used satan keyboards with tmk key map generator, it looks something like below.
![image](https://user-images.githubusercontent.com/13689413/129444422-ae8d2b69-aeab-48cd-a858-3fb2fdfb1819.png)
