### ISSUE TITLE
How to run the GUI on Mac?

### ISSUE THREAD

**Issue by andomeister** [pixeltris/GK6X#63]
I've pretty much figured out how to run the build in mono, but I don't really get how to run the webGUI

**Comment by pixeltris** [comment]
Once the tool is running you just type 'gui' in the command line. Someone made a video here if you're having troubles with it https://www.youtube.com/watch?v=kTkSzDxonMw

**Comment by andomeister** [comment]
Success. Of course it was simpler than I assumed. Thanks for the help!

**Comment by ymsrk** [comment]
Thank you for answering and verifying my question.
it's succeed by the latest commit 26c0aa7
Thanks for the help!
