### ISSUE TITLE
Weird gui format

### ISSUE THREAD

**Issue by RShemmy** [pixeltris/GK6X#65]
whenever i do the gui command the gui is all scrunched up and in weird format
![cture](https://user-images.githubusercontent.com/58443415/90177318-5d56b900-dd78-11ea-8c5d-76fc09af2208.PNG)

**Comment by RShemmy** [comment]
Also the reason i'm on v1.8 is because this issue was also occurring on the new v1.9

**Comment by pixeltris** [comment]
Yea you have to resize the window to an aspect ratio that the UI likes. The original UI was designed at a specific resolution / aspect ratio, so if you use something different to that it can look a bit funky.

**Comment by RShemmy** [comment]
Ok thanks for the help

**Comment by RShemmy** [comment]
I cant explain my gratitude to you thank you so much, I couldnt get the normal GK6XPlus to work and yours works. Thanks so much again.
