### ISSUE TITLE
[Question] Different between TempSwitchLayer1 and Layer1Button

### ISSUE THREAD

**Issue by cheuksing** [pixeltris/GK6X#68]
There's are 2 different kinds of switching layer buttons, mentioned in
https://github.com/pixeltris/GK6X/blob/81761765f020962ed04ad68f8f0837facda7a1fa/GK6X/KeyValues.cs#L460
https://github.com/pixeltris/GK6X/blob/81761765f020962ed04ad68f8f0837facda7a1fa/GK6X/KeyValues.cs#L503

What are the differences?

I learned that the FnBase layer isn't customizable.
As a workaround, I am planning to set Layer1 as the default layer permanently.

Is this what Layer1Button do?
Will unplug / power off change the default layer backed to the base layer again?

**Comment by pixeltris** [comment]
A key mapped to TempSwitchLayer will temporarily switch the keyboard to that given layer for as long as you hold down the key you mapped to TempSwitchLayer. The other kind of layer switching will stay on the target layer after you release the key. So yes you can use Layer1Button to go to Layer1 indefinitely (or use the built-in key combo to go to Layer1).

I think the keyboard should remember which layer it was on after unplugging it. Not 100% sure on that though.

**Comment by YourFriendCaspian** [comment]
What's the difference between a Layer and a FnLayer, like Layer1 and FnLayer1? Sorry for globing onto someone else's question but I thought it was easier because they are sort of similar.

**Comment by pixeltris** [comment]
Layer1 represents all keys on layer 1. FnLayer1 represents all keys on layer 1 whilst the Fn key is held down.

For example if you were to map A->F on Layer1 and you pressed the A key you would get 'F'. If you were to map Q->F on FnLayer1 you would first need to hold down the Fn key to get an 'F' when pressing 'Q'.
