### ISSUE TITLE
Switching computers doesn't remember settings

### ISSUE THREAD

**Issue by bdnorris** [pixeltris/GK6X#69]
I may have a fundamental misunderstanding of what this software does, so I'm wondering if this is expected behavior. I have two Macbooks that I use my keyboard on, one for work and a personal one (one computer is on MacOS 10.14, the other 10.15). When I switch computers, I have to run the software again to re-apply my settings. 

Steps to reproduce:

1. run `sudo mono GK6X.exe`... run `gui`. 
2. use the GUI to setup customizations
3. use the "Apply" button to apply settings
4. plug keyboard into the second computer, repeat steps 1-3. 
5. plug the keyboard into the first computer, settings are no longer applied. 

Steps to fix:

- repeat steps 1 and 3, every time plugged into a different computer. 

Note that I don't have to set up any customizations, just hit the apply button. 

Is this expected, or is there a way to get the settings to "stick"?

**Comment by pixeltris** [comment]
The settings should stay on the keyboard. However, if you open the gui on another machine you wont see the settings that are on the keyboard as the keyboard doesn't ever broadcast its current config to the PC. Therefore it's recommended to use a single machine to configure your keyboard as otherwise you will have to re-create any previously configured keys.

**Comment by bdnorris** [comment]
I am sure that once I configured it the first time on one computer, I had to configure it again on the second one, so I figured the config was saved on the computer. It's the exact same config on both machines either way.

Could it be that the keyboard is losing it's config when it's unplugged for too long? I have the GK64x and it does not have BlueTooth so it doesn't have a battery. Sorry, this is my first keyboard that allowed more than software configuration so I don't know much about how it works.

**Comment by pixeltris** [comment]
It should definitely save on the keyboard. If it isn't saving then I'd recommend trying the official software. If it still doesn't save I'd suggest contacting where you got your keyboard to ask about getting a replacement.

**Comment by bdnorris** [comment]
Gotcha, thank you very much for the information.

**Comment by bdnorris** [comment]
FYI, for anyone with a similar problem: The issue was I was in "Standard Mode". When I switched to "Onboard Mode 1" by using Fn + W, then applied the settings, the keyboard now remembers them.
