### ISSUE TITLE
Temp Layer Switch key issues

### ISSUE THREAD

**Issue by noclew** [pixeltris/GK6X#70]
Hello, thanks for the wonderful software. By the way, is it possible to disable the base key of the temp layer switch? For example, if I use the smallest left space bar key in the split spacebar set up as a layer switch key, it still registers a space bar when pressed alone. However, I'd like to use that key solely for layer switching, which makes more sense I think. Is it possible?

**Comment by pixeltris** [comment]
Some keyboards under the GK6X line have a special spacebar key which is hard coded into the firmware which exhibits this behavior. Unfortunately I don't believe there's any way to remove the space key functionality (which limits the usefulness of that whole split space bar thing imo, but hey ho).
