### ISSUE TITLE
Lighting Effect Settings Greyed out

### ISSUE THREAD

**Issue by DCHRISANGELO** [pixeltris/GK6X#73]
My Lighting Effect Settings are greyed out. Cycling through the layers don't seem to do anything.
Would really appreaciate a solution.
<img width="995" alt="Screen Shot 2020-09-12 at 05 28 03" src="https://user-images.githubusercontent.com/69384448/92978018-c127eb00-f4b8-11ea-9dfa-22be29af0b76.png">

**Comment by pixeltris** [comment]
Some keyboards don't support custom lighting on anything other than the base layer. If you believe it's a mistake and it should work (as such as is the case with GK84) then you can follow the steps provided here https://github.com/pixeltris/GK6X/releases/tag/GK6X-v1.9
