### ISSUE TITLE
How can I help making this compatible with my KEMOVE Snowfox?

### ISSUE THREAD

**Issue by RmigD** [pixeltris/GK6X#76]

**Comment by RmigD** [comment]
I believe there is a DK61 underneath this...

**Comment by pixeltris** [comment]
I updated the data files. It might be worth checking if it works now?

**Comment by RmigD** [comment]
When I connected it, nothing happened, so I assumed it didn't work. Even their website calls it a DK61...
https://kmovetech.com/c/kemove-dk61-snowfox-0395
I might have messed up. I'll try again another time.

**Comment by pixeltris** [comment]
It looks like if it's the `DK61 Pro` model it should work. The `DK61E` model seems to use some other software https://kmovetech.com/art/https-kmovetechcom-software-download.html

**Comment by RmigD** [comment]
I tried again today from scratch and no luck. Nothing pops up when I run 
`sudo mono GK6X.exe`

I get this from lsusb:
`Bus 002 Device 020: ID 1ea7:9005 SHARKOON Technologies GmbH Turing Gaming Keyboard`

What can I do?

**Comment by pixeltris** [comment]
https://github.com/pixeltris/GK6X/commit/9bd09b4a96fe26c01dad24a6f0fe73008e0509a7 should add the missing KEMOVE data files.
