### ISSUE TITLE
[Question] Need a little help with the config txt file please 

### ISSUE THREAD

**Issue by YourFriendCaspian** [pixeltris/GK6X#77]
I have a few quick questions on creating my config file to upload to my GK68XS. When I'm mapping keys on a layer, does each key have to have the header, ie. [Layer1], or can I map multiple keys under the same header? Example-
[Layer1]
D1:F1
D2:F2   or

[KeyAlias]
LeftSpace:Space_2
LeftSpace:Space_3

Then on lighting effects, I created an le file to have different keys be be different colors on layer1 so that I know I'm actually on it. But after I added the file to my config file it does seem to work. The WSAD Static.le I used as the example doesn't have all the fields that other le files do. Can my le file be as basic as the example or do I need fields like "Name":"frame0" and all the other stuff? This is what it looks like in my config-
[Lighting(yfc-layer1,Layer1)]

This is an amazing project that makes my keyboard sop much better and easier. Thank you very much for all your help and hard work,
yourfriendcaspian

**Comment by pixeltris** [comment]
The first mentioned scenario would work

```
[Layer1]
D1:F1
D2:F2
```

The key alias you mentioned wouldn't work. It's one unique name per alias. For GK68XS what might make sense is:

```
[Layer1]
MidSpace:Space_2
RightSpace:Space_3
```

Though I'm not 100% sure on the namings of the Space_X, you'd have to check with dumpkeys to ensure you've got the correct names.

For static lighting you can follow the same approach as in `WSAD Static.le`. It might be that the contents of your le file is malformed for some reason, try duplicating `WSAD Static.le` and adding one key at a time. Frames are used for animated lighting effects. For more complicated lighting effects it might be recommended to use the GUI to create the lighting effect files, and then copy them over via the `gui_le` command. See https://github.com/pixeltris/GK6X/issues/62#issuecomment-670667390

**Comment by YourFriendCaspian** [comment]
Oh yeah, I accidentally missed typed my alias example but none the less you answered my questions. Another question, while I'm holding a TempSwitchLayer key, will it switch to that layers lighting effect if I use the example above or is that FnLayer instead of just Layer? Thank you very much for all your time and help. I really appreciate it.

**Comment by pixeltris** [comment]
For GK68XS I believe there isn't support for different lighting on different layers. I think that's the case with most of the newer GK boards. Some of the older boards will switch the lighting whilst TempSwitchLayer is held down I believe. Fn layer doesn't have its own lighting but I've heard mention if there being lighting effects on some boards which do have separate lighting effects for the Fn layers but I'm not sure how to configure those.
