### ISSUE TITLE
Disable FN layer active layer light

### ISSUE THREAD

**Issue by samiyuru** [pixeltris/GK6X#78]
This is a very cool project.

When you press the FN button when you are in a layer other than the standard layer, W, E or R light up to indicate the layer you are in. Is it possible to disable that light with this tool?

**Comment by pixeltris** [comment]
Which board are you using? There was mention of this being the default behavior in https://github.com/pixeltris/GK6X/issues/27

After they re-mapped lighting effects via this project it actually wiped over the fn layer lighting and they couldn't get it back. So if you want to remove this behavior try applying custom lighting effects. But beware as I don't know how to restore fn layer lighting. I guess it might be opcode 0x23 or opcode 0x24 https://github.com/pixeltris/GK6X/blob/ae10b1367dd0cc38084c0b90a1ceb5fac7b677d2/GK6X/OpCodes.cs#L54

**Comment by samiyuru** [comment]
Thanks for the info. I am planing to use a nonstandard layer as the default layer, I do not have plans on restoring the original functionalities. I am okay as long as I can customize anything in one layer :)

**Comment by samiyuru** [comment]
Seems like we can not disable the active layer indication light since some keyboards do not allow to apply light effects on layers as pointed out in another issue #79.
