### ISSUE TITLE
Light effects on layers other than the base layer do not work

### ISSUE THREAD

**Issue by samiyuru** [pixeltris/GK6X#79]
This was tried on GK61XS.

I added the following to the key mapping text file.

[Lighting(Windmill,Base)]
[Lighting(Red Light Breathing,Base)]
[Lighting(Star lighting,Base)]
[Lighting(WASD static,Layer1)] 

After map is successful I activated layer 1 using _Fn + W_. 
Only the effects from the base layer are available when switching effects using _Fn + ]_.
I did not see 'WASD static' when going through the effects. 
When I applied the same for the base layer it is available to be enabled in all layers.

**Comment by pixeltris** [comment]
Unfortunately some keyboard don't support different lighting effects on different layers. Keyboard flagged with `"hasModeLe":false,` in their config.json cannot map lighting effects on a per-layer basis.

**Comment by samiyuru** [comment]
Okay. Thank you.

When are those config files used by the program?

**Comment by pixeltris** [comment]
I'm not sure if the .config file is loaded in this project at all. But they are loaded by the official software to determine how to set up the GUI and things (in the case of `hasModeLe` the GUI will disable the lighting effect panel for keyboards which cannot configure the lighting effects on different layers).
