### ISSUE TITLE
Remapping ESC key to use as primary "~" 

### ISSUE THREAD

**Issue by rolandinhobr** [pixeltris/GK6X#80]
Hello!

I'm from Brazil and i really need to use ~ and ` a lot to type. So, i want to use my ESC key like this:

When i press ESC, results in "`"
When i press SHIFT+ESC, results in "~"
When i press FN+ESC, results in ESC function

The problem is: i cant change the ESC key to ~ because this caracter isn't listed in the original software for GK64. I also tried to make a macro, but i couldn't find a way to use FN key inside macros in the original software.

Please, help me!! I'm in love with my new homemade keyboard, but i cant use it :/
If you guys just type the .txt for me, i will use it with the GK6X prompt software from this github.

Thanks A LOT :)

**Comment by pixeltris** [comment]
[Base,Layer1,Layer2,Layer3]
Esc:BackTick

Assuming Esc isn't mapped to anything on the fn layer by default Fn+Esc should default to Esc.

**Comment by rolandinhobr** [comment]
Thanks a lot! Worked like a charm!

But i cant use ESC now. Even if i press "FN+ESC" i still make `.

And if i double press FN to go to Fn layer, still the same ```. 

To be perfect, i need to make ESC function with FN+ESC without entering the Fn layer, just using FN+ESC.

Again, thanks, you are saving my life rsrs

**Comment by pixeltris** [comment]
Fn+Esc is probably default mapped to backtick then. So you would want the following (note that yoy cant remap base fn layer, so you would need to make layer1-3 your default layer)

[FnLayer1,FnLayer2,FnLayer3]
Esc:Esc

**Comment by rolandinhobr** [comment]
Done! You are my hero!

**Comment by veronikazaglotova** [comment]
> Done! You are my hero!

If it's fixed, please, close the issue.
