### ISSUE TITLE
Power/Sleep key

### ISSUE THREAD

**Issue by skibbipl** [pixeltris/GK6X#81]
I would like to map Fn+some key to Power/Sleep button. I cannot find the keycode for this button. Is GK61XS keyboard supporting power/sleep key?

**Comment by pixeltris** [comment]
It looks like it's called `Power`. I'm not sure if I've tested it, but if it works it should work on all GK6X keyboards.

**Comment by skibbipl** [comment]
Yeah, that is what I did in the mapping:
 ```
[FnLayer2]
P:Power
```
But nothing happens. Also according to [keycodes](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) sleep button should return 0x5F but my mapped button returns 0xFF

**Comment by pixeltris** [comment]
I think the way I came to the value of `Power` was by trying different values on a website which displayed the keycodes, and that one displayed `Power`. I'm not sure what it's actually used for.

You'd need to find a GK6X keyboard with a power key to find the actual key code.

**Comment by skibbipl** [comment]
Yeah, probably they forgot about this button to the firmware :( Nice board but software-wise sucks totally...
