### ISSUE TITLE
GK64 - Lights turn off after a while (pressing capslock turns them back on)

### ISSUE THREAD

**Issue by distresscode** [pixeltris/GK6X#82]
Hi, 
Is there a command to force the lights to stay on all the time? 
Thanks!

**Comment by pixeltris** [comment]
I haven't observed this behavior. Maybe this happens on keyboards in bluetooth mode. That would be a firmware controlled thing so there isn't much that can be done about that.

**Comment by distresscode** [comment]
you got me checking if my keyboard has bluetooth because I didn't think my model did and that led me to find out that I can press FN + LCtrl multiple times to set it to 0 (which is to never turn off) so thanks for the fix 👍
