### ISSUE TITLE
Is it possible to bind the macOs native functions like changing screen brightness (GK68XS)?

### ISSUE THREAD

**Issue by mplusp** [pixeltris/GK6X#84]
I'd like to be able to control the brightness of my screen via keyboard hotkeys.

Is this possible with the GK68XS? It seems to be possible with the upcoming [GK96](https://gk96.epomaker.com/)

Thanks in advance.

**Comment by pixeltris** [comment]
The data files for that keyboard are already available. Looking at the values it doesn't appear as though they have any special separate values, F1 is just listed as F1.

https://github.com/pixeltris/GK6X/blob/ae10b1367dd0cc38084c0b90a1ceb5fac7b677d2/Build/Data/device/656801853/data/profile_offline_1.json#L1582

It might work via some special communication as I don't think brightness key codes actually exist as a standard thing (they are always implemented as special cases, and not just picked up by the OS).

**Comment by mplusp** [comment]
I didn't have time to look into that yet (and also not really into the text files for the cli tool), but I think, that the brightness function is activated by pressing fn+f1/f2. Can we see what value is send when pressing those key combinations from the file you linked?

Thanks for your help 👍

**Comment by pixeltris** [comment]
The keyboards never send the key values that they use internally (which are called "DriverValue"). They are only defined in the firmware itself and the data files. So you either need a way to dump the firmware or rely on the value being in the data files (which doesn't seem to be the case). This could be an indicator that it's a hard-coded thing in the firmware and there might not be an associated "DriverValue".

**Comment by willerbee** [comment]
@mplusp Print Screen and Scroll Lock keys are being interpretted as Brightness Up and Down in macOS. If you're looking for the closest behavior to an apple keyboard, use an app called Karabiner Elements

**Comment by pixeltris** [comment]
Using additional mapping software is probably the most viable option as there doesn't seem to be an indication that there's an applicable `DriverValue` for these keys.
