### ISSUE TITLE
Is'GK64XS-RGB'not supported?

### ISSUE THREAD

**Issue by ymsrk** [pixeltris/GK6X#87]
Hi please help me

run `sudo mono GK6X.exe`

```
Couldn't find data path
Connected to device 'GK64XS-RGB' model:656801805 fw:v1.17
Disconnected from device 'GK64XS-RGB'
```

Is'GK64XS-RGB'not supported?

**Comment by pixeltris** [comment]
I might have broken things in my latest commit which tried to detect if it's being run in GUI mode. I'll undo the code and revisit the check at some point.

https://github.com/pixeltris/GK6X/commit/156fa9e9d6d2729822b9b1b4085471fbe934480f#diff-9933b2fc80832cca65414fe28cd5cda97578ca3d7d1db7ebc5065e5cbb7bc2a1R41

**Comment by pixeltris** [comment]
Should be fixed by the latest commit https://github.com/pixeltris/GK6X/commit/26c0aa775767708ed0a62f31310df44d62cf284f

**Comment by ymsrk** [comment]
Thank you for answering and verifying my question.
it's succeed by the latest commit 26c0aa7
Thanks for the help!
