### ISSUE TITLE
[Question] Do you have a guide on how to set lightning?

### ISSUE THREAD

**Issue by veronikazaglotova** [pixeltris/GK6X#88]
I want my Esc key to be lit up with a different light on different layers. No need to have complex animations (although this might be helpful for anyone else who wants it), just the whole keyboard lit up with a one color and an escape key with a different color.
I opened your .le files and I don't quiet understand how it should work. A guide (or an explanation) would be helpful. I don't currently have the official driver to check, but as far as I know https://github.com/pixeltris/GK6X/blob/master/Build/Data/lighting/61%20Arrow-Key.le should turn on /?, Alt, Menu, Ctrl keys to red, showing arrow keys. But it's not clear how it achieves that. What are these numbers? I understand that every number corresponds to a key, but I don't know which key it is, unless I explicitly check it on my own keyboard, constantly rewriting the file and loading the .txt file to my keyboard.
I can make it in GK6X+ and decrypt it (I guess?) or use the GUI GK6X, but that's just a workaround, I'd like to use the CLI version if possible.

**Comment by pixeltris** [comment]
There's a command `gui_le` which decrypts/copies lighting effect files created via the web GUI (though it doesn't currently copy any files from the official GUI). https://github.com/pixeltris/GK6X/issues/62#issuecomment-670667390

The lighting effect files provided are just the decrypted ones from the official software, which were most likely made in the official GUI. The format for them isn't super intuitive. I honestly couldn't tell you without re-reading the files/code related to them. I did add support for using key names which you can see https://github.com/pixeltris/GK6X/blob/master/Build/Data/lighting/WASD%20static.le which does basic static color mapping.

I'm not sure which keyboard you have, but only certain keyboards support different lighting data for different layers. The ones which don't support it, will carry over the lighting effects to all layers.

**Comment by veronikazaglotova** [comment]
hi! It works on GK61 with official software so should work with GK6X too.
thx for the names
does it use the same names as in the .txt file, e.g. from the [KeyValues.cs file?](https://github.com/pixeltris/GK6X/blob/81761765f020962ed04ad68f8f0837facda7a1fa/GK6X/KeyValues.cs#L269)
If yes I think I can close the issue

**Comment by pixeltris** [comment]
Yes it should be the names found in KeyValues.

**Comment by veronikazaglotova** [comment]
Thx a lot
