### ISSUE TITLE
[Question] GK64S change sleep timer

### ISSUE THREAD

**Issue by julialtmeyer** [pixeltris/GK6X#89]
Hello,
I am not sure if this is possible with how this software is reprogramming the keyboard, but is it possible to change the time before the wireless keyboards go to sleep? I always find myself trying to type something only to have to wait for the keyboard to reconnect and its getting pretty annoying.
Thanks!

**Comment by pixeltris** [comment]
I don't believe so. This would likely require a change in the firmware. It might be a trivial firmware change which could be done via a hex editor, but firmware files aren't downloadable for the majority of the keyboards.

**Comment by julialtmeyer** [comment]
That's a shame, thank you for your help though!
