### ISSUE TITLE
only 1 macro allowed

### ISSUE THREAD

**Issue by madcat820** [pixeltris/GK6X#9]
I have the following simple test script, seems that no matter format i do, it only runs the first macro it sees.
Your help sir is gladly appreciated.

#================================
[Layer1]
RShift:Home
Z:N

[FnLayer1]
D:Macro(MyMacro1)
RShift:Macro(Dos)

[Macro(MyMacro1,0,PressKeyAgainToStop)]
Down:W:3000
[Macro(Dos,0,PressKeyAgainToStop)]
Down:S:3000

[Lighting(Violet Light,Layer2)]
#=============================================

**Comment by pixeltris** [comment]
I'm not sure I tested more than 1 macro so it could be that I messed something up such as the 2nd macro wiping over the 1st, or sending an invalid macro buffer size. I'll try looking at this over the weekend.

**Comment by madcat820** [comment]
Thank you so much for your hard-work on this, ill be standing by on this project as this is so robust and more complete than the crappy stock software.

**Comment by madcat820** [comment]
I think once the issue with the macros got fix, this will be the best solution for the crappy software, its so robust and has a lot of things it can do that the stock firmware software doesn't have

**Comment by pixeltris** [comment]
Should work now (I missed writing a byte at the end of the macro packet). Let me know how it goes.

**Comment by madcat820** [comment]
Man, thank you so much, im new to github , i just read around, recompiled your new commits and it worked now, this should go to the release section so others may benefit. The software feels so complete now. Thanks again.

**Comment by pixeltris** [comment]
Oh yea I forgot I even made a release. I'll do that soon, thanks.
