### ISSUE TITLE
Unable to map anything on my GK64

### ISSUE THREAD

**Issue by edwinkwlee** [pixeltris/GK6X#90]
[23:23:11.9580905] Connected to device 'GK64 RGB V1' model:656801802 fw:v1.5

```
[Base,Layer1,Layer2,Layer3]
Right Control:Delete
```
Running GK6X-v1.11 release

**Comment by pixeltris** [comment]
The supported key names can be found here https://github.com/pixeltris/GK6X/blob/d1a1d8047966a917c0b82fe96e693c5a79654d7b/GK6X/KeyValues.cs#L269

So the mapping should be:

```
[Base,Layer1,Layer2,Layer3]
RCtrl:Delete
```

**Comment by edwinkwlee** [comment]
Ah, got it. I tried previously and thought it wasn't working.
I have mistaken dumpkeys to show all my current key mappings. I
