### ISSUE TITLE
Latest version detected as virus

### ISSUE THREAD

**Issue by highfredo** [pixeltris/GK6X#91]
Hi,

Last version of this awesome project is detected as a virus by Windows Defender.

Screenshot in Spanish, but I think it will be useful
![image](https://user-images.githubusercontent.com/5951524/101266290-bb574400-374d-11eb-96e6-568862479f89.png)

**Comment by pixeltris** [comment]
Weird, not sure why that would happen. I haven't changed anything about the build process. Maybe it doesn't like this code:

https://github.com/pixeltris/GK6X/commit/156fa9e9d6d2729822b9b1b4085471fbe934480f#diff-9933b2fc80832cca65414fe28cd5cda97578ca3d7d1db7ebc5065e5cbb7bc2a1R113
