### ISSUE TITLE
question about remapping ESC on GK68XS (but slightly different from issue #80)

### ISSUE THREAD

**Issue by wingsof** [pixeltris/GK6X#92]
Hello,

I was trying to remap my ESC key of GK68XF with the following key but failed to find the way.

ESC -> ESC as usual
(Right) Shift + ESC -> `
(Right) Shift + (Right) Alt + ESC -> ~

Is it possible to map like above or should I use macro to map that?

Thank you for the awesome software and your help!

**Comment by pixeltris** [comment]
I'm not sure if the second part of that would work, but here would be a mapping for that:

```
[Base,Layer1,Layer2]
RShift:TempSwitchLayer3

[Layer3]
Esc:BackTick

[Layer3]
RAlt:RShift
```

**Comment by wingsof** [comment]
oh it worked perfect for esc key but make right shift unavailable for other keys.
with that setting, pressing 1 + RShift prints just 1 not ! character... ;-(

**Comment by pixeltris** [comment]
Yea, unfortunately there isn't any way to make Shift+Esc have separate functionality.

**Comment by flocc** [comment]
@wingsof @pixeltris There is a workaround, example:

    [Base]
    RShift:TempSwitchLayer3

    [Layer3]
    ESC:LShift+BackTick
    D1:LShift+D1
    ...

So RShift + ESC will give you tilde(~) and RShift + 1 will give you ! as expected.
Just map everything else like this.

I got GK61x yesterday and had almost same issue - wanted to mimic Grave Escape from QMK. 
You can also do things like RShift + LShift -> CapsLock etc.
The worst thing is you cannot remap default Fn key, I'm so used to have RCtrl here :)
