### ISSUE TITLE
Press Light

### ISSUE THREAD

**Issue by kypi** [pixeltris/GK6X#93]
The base software allows us to map a press light and a function light for each layer (so we can have custom lighting from a keypress). 
Is this possible with this software? I looked at the sample.txt and didn't see anything that would let me, say, map light profile for when I hit w or s.
![image](https://user-images.githubusercontent.com/5155266/101274135-39711600-3761-11eb-815c-4e2c6e28255e.png)

**Comment by pixeltris** [comment]
I didn't code that functionality as the effects abruptly cut off. This would need to be implemented to get this functionality https://github.com/pixeltris/GK6X/blob/d1a1d8047966a917c0b82fe96e693c5a79654d7b/GK6X/OpCodes.cs#L60

**Comment by pixeltris** [comment]
Closing this as there aren't any plans to implement this functionality.
