### ISSUE TITLE
Ordering of modifiers matter when using temp layer switch

### ISSUE THREAD

**Issue by lagwagone** [pixeltris/GK6X#94]
I have the following config to use CapsLock plus IJKL as arrow keys for my 'GK61XS RGB'

[Layer1]
CapsLock:TempSwitchLayer2

[Layer2]
I:Up
J:Left
K:Down
L:Right

In notepad if I use Ctrl + Caps + L to jump to the end of a word it doesn't work (cursor only moves one letter to the right). 
However if I use Caps + Ctrl + L then it does work. 

Is there anyway around this? Still not possible to assign CapsLock to the Function key?  CapsLock:Fn

Thanks,

**Comment by pixeltris** [comment]
No, unfortunately both of those are limitations of hard coded functionality of the firmware.

There might potentially be an Fn DriverValue, but I haven't been able to find it, so it's likely also a hard coded firmware thing.
