### ISSUE TITLE
GK61XS stuck at connecting

### ISSUE THREAD

**Issue by ForsakenRei** [pixeltris/GK6X#95]
Hi there,

I'm on Win 10 20H2 and trying to remap the Fn key. While I run the .exe as admin and reconnect the keyboard, it will only show
"Connected to device 'GK61XS RGB' model:656801835 fw:v1.17"
that's all. Any suggestions?

Thanks.

**Comment by pixeltris** [comment]
That sounds like it's operating as expected. Did you read https://github.com/pixeltris/GK6X#usage ?

**Comment by ForsakenRei** [comment]
Yes so maybe I understand it wrong.
After connected, it will generate a txt file, 656801835.txt and it is supposed to be empty. Then I need to write what key I want to map to what in the txt file then use map to map them(I assume I don't need to list all the keys that I didn't want to change?) to the keyboard. Does it sound correct?

**Comment by pixeltris** [comment]
Yes that's correct. There's a couple of examples of mappings, and the names of all the keys in the sample .txt file https://github.com/pixeltris/GK6X/blob/master/Build/UserData/Sample.txt

**Comment by ForsakenRei** [comment]
Yeah I did see the sample. Thanks for the help!
