### ISSUE TITLE
all WAS okay

### ISSUE THREAD

**Issue by TKSHII** [pixeltris/GK6X#96]
hello
i mapped my sk64 everything was great
i launched counter strike then my keyboard was disabled
GK6X.exe cant found my keyboard now, help pls

**Comment by veronikazaglotova** [comment]
Try reconnecting?

**Comment by TKSHII** [comment]
He is working now because i bought a bluetooth adapter but with the usb only it doesnt work.
I had to change usb port for get the "Connected" but even if i see that my keyboard loss connection with the program instantly
Is there a solution for map keys with the GUI program even if i use the keyboard in bluetooth and not in usb ?
Because i'm on an ANSI US 64Key keyboard and i'm usually on a french ISO azerty layout. So i really need to remap some keys

**Comment by veronikazaglotova** [comment]
> He is working now because i bought a bluetooth adapter but with the usb only it doesnt work.

Sounds like a hardware issue to me

**Comment by veronikazaglotova** [comment]
By the way, as a workaround, you can use Autohotkey to remap keys or utilities made for GNU/Linux.
If you're on GNU/Linux, as a last resort, you can restore your keyboard to defaults with Fn+Esc+Q and then use the xkb utility to make Caps Lock behave as ISO <> key (the one that turns a into à or á). I can help you with that if you want to.

**Comment by TKSHII** [comment]
Hello, i'm searching how to do this since one week, so if you give me your help, i take it :+1: 
I got discord if you want.
And i googled "Autohotkey Linux" and i found this program : https://github.com/Paris/IronAHK
I'm gonna try it today.
Thanks you for your time !

**Comment by veronikazaglotova** [comment]
>  https://github.com/Paris/IronAHK

This project is dead and it's unlikely to work with newer X.Org versions. Use autokey, it's an alternative for AHK IIRC. If you need to make one key output another key, you can use xkb for that, it's already installed and is relatively easy to use.

**Comment by pixeltris** [comment]
The only thing I could suggest doing is using the keyboard reset combo as mentioned https://github.com/pixeltris/GK6X/issues/96#issuecomment-748430424

**Comment by TKSHII** [comment]
Can you tell me more about xkb ?

**Comment by veronikazaglotova** [comment]
Read this https://gist.github.com/toroidal-code/ec075dd05a23a8fb8af0
Read other files from the symbols directory to find out how every key on the keyboard is called. 
And this https://help.ubuntu.com/community/Custom%20keyboard%20layout%20definitions?action=show&redirect=Howto%3A+Custom+keyboard+layout+definitions
https://askubuntu.com/questions/684459/configure-caps-lock-as-altgr-and-arrows-like-in-vim/898462#898462
