### ISSUE TITLE
Disable CapsLock light

### ISSUE THREAD

**Issue by jayk** [pixeltris/GK6X#97]
Hello!

I have a GK64 (model 656801836) I've created a very simple keymap which remaps CapsLock to Escape:

`[Base,Layer1,Layer2,Layer3,FnLayer1,FnLayer2,FnLayer3]
Caps Lock:Escape
Esc:BackTick`

It works, and when I press CapsLock, I get an Escape character... BUT... the caps lock light still toggles.

Is there a way to make the CapsLock light no longer toggle?

Thanks!

Jay

**Comment by pixeltris** [comment]
Unfortunately this the lighting of the caps key is hard coded in the firmware, and there isn't any way to control it via software.

**Comment by jayk** [comment]
ah, bummer.  I was worried that was the case... That's ok then.  I'll live with it.  Thanks for the confirmation. :smile:
