### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by Bhanukamax** [pixeltris/GK6X#98]
Hi I'm on linux, would be great if build steps can be added to readme, 

I didn't find any thing like a `Makefile` on the repo, please provide some directions, happy to update the readme if i can get some clue on where to start, thanks

**Comment by pixeltris** [comment]
The README.md states how to compile it `It can be compiled / ran with mono on Linux / Mac (see #4). On Windows you compile it with Visual Studio.`

Or there are precompiled binaries https://github.com/pixeltris/GK6X/releases

**Comment by Bhanukamax** [comment]
Hi thanks for the swift reply, sorry about the oversight, I managed to build it and when I run it it just hangs there and doesn't  give any prompt or any thing. this was the case with the binaries i downloaded from the release page as well:
![image](https://user-images.githubusercontent.com/8494781/102693495-ff177680-4240-11eb-8197-6d8168d4a783.png)


Am i missing something here?, sorry about the confusion, I'm very much a newbie when it comes to c# and mono stuff

**Comment by Bhanukamax** [comment]
Hi  thanks for the swift reply, I looked in to the [issue](https://github.com/pixeltris/GK6X/issues/4) mentioned on the read me, got all working with mono, even the pre build bineries can be run with it. Thanks a lot
